### ISSUE TITLE
Search: automatically show shortcuts/favorites/(smart) recents/tag

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#100]
**Description**

1. When opening the search, the result list is empty. It would also make sense if the user could choose what to show initially upon opening search, in order to decrease the amount of taps further for some actions. For example, the user chooses to display the subset shortcuts/favorites/(smart) recents/tag directly.

2. This should not, however, mean that you have to press twice to activate another filter (as is the case when switching from one filter to another via the quick list). To be honest, I don't know why you should press twice in the first place. Should this be fixed?

**Comment by TBog** [comment]
Does [build v6.0-dev.3](https://github.com/TBog/TBLauncher/releases/tag/v6.0-dev.3) fix this issue?

**Comment by ltGuillaume** [comment]
Yes, it totally does! 👍 Thank you! 😃

**Comment by TBog** [comment]
You should be able to by long touching the ✖️ button

**Comment by ltGuillaume** [comment]
Aaaah ok. Takes a bit of getting used to (and I don't see any use for the ✖️ button when you explicitly chose to show a results set) but I'll adapt.

**Comment by TBog** [comment]
The ✖️ button is used to close the result list and allow me to tap the screen to go to the widgets.

**Comment by ltGuillaume** [comment]
Ah for the fling/tap gestures, yes, I understand now 👍

**Comment by ltGuillaume** [comment]
I found a bit of a drawing issue with this: the search bar and keyboard open, then the history shows, but then the quick list opens last, which makes the history items jump upwards. It would be best if search bar and quick list items were drawn before the result list is filled with the history items. Also, I see an animation when the quick list icons appear, but not with the history items.

**Comment by TBog** [comment]
Please open an issue as it's hard to keep track of comments on closed issues.

Also, please put steps to reproduce the issue and possible setting you have that might change the behavior.
