### ISSUE TITLE
Results ScrollView size stuck to region above already hidden keyboard until releasing finger

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#101]
# Description #

I don't know if it's possible to fix, but it would be nice if the ScrollView of the results list would grow instantly at the moment the keyboard is hidden by scrolling. Currently, the scrollView only grows towards the bottom as soon as you release your finger.
If this is not reproducible, then this might also have something to do with the keyboard app I am using.

## Steps to Reproduce ##

To reproduce the behavior:
1. Go to the search
2. Type something, so results pop up
3. Scroll the results list, so that the keyboard is hidden and _keep your finger on the screen_.
4. The scrollView of the results list remains stuck at the top half of the screen.

### Video ###
![Video of the issue](https://user-images.githubusercontent.com/4777345/105606473-e2b7ae00-5d99-11eb-991d-3abb477f2976.mp4)

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: Preview build https://github.com/TBog/TBLauncher/issues/70#issuecomment-765472295

**Comment by TBog** [comment]
I think this is something I inherited from KISS. Not sure if something else will break regarding scroll if we change this.

I'll look at this when there are no other more pressing issues.

**Comment by ltGuillaume** [comment]
Thanks, I hope it's possible to fix. https://github.com/Neamar/KISS/issues/408 seems to discuss it, too.

**Comment by ltGuillaume** [comment]
I just tested KISS regarding tis issue and it isn't present there (anymore).

**Comment by ltGuillaume** [comment]
Did you find out how KISS fixed this?

**Comment by TBog** [comment]
> Did you find out how KISS fixed this?

I already had the fix, but because the layout is different the keyboard height was not detected properly.

**Comment by ltGuillaume** [comment]
Noice! 😎

**Comment by ltGuillaume** [comment]
Works in 6.1dev.1!
