### ISSUE TITLE
Gesture "Open settings" actually opens Notifications

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#102]
# Description #

I tried all swipe gestures to open Settings, but instead they open the Notifications.

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: preview build https://github.com/TBog/TBLauncher/issues/70#issuecomment-765472295

**Comment by TBog** [comment]
`Show settings panel` does work on my Samsung Galaxy S20+ with Android 10 and Emulator Android 7.0.
Maybe your device does not have that feature. As a fail-safe in case the settings panel can't be opened (as it's not part of the public Android API) I open the notifications.

Any other launcher that does open the settings panel on your device?

**Comment by TBog** [comment]
I think Android 11 added some new notification panels that can be opened with Intents, I'll look into it when I get to adding more gesture actions.

**Comment by ltGuillaume** [comment]
I'm on Android 10, so that would be a new problem.

To be honest, I haven't used launchers to open the settings panel yet, only custom ROM features to do so (swipe down from status bar at left side instead of right side, for example).

**Comment by TBog** [comment]
Does this still happen in the latest build you tested?

**Comment by ltGuillaume** [comment]
Yes, it does

**Comment by TBog** [comment]
I'm sorry then, I can't replicate the issue so I can't fix it.
Need help.

**Comment by ltGuillaume** [comment]
Too bad then, no biggie. How about

> This could also be achieved for the user if a new option "Run app/shortcut" would be added as a gesture action.

**Comment by TBog** [comment]
> This could also be achieved for the user if a new option "Run app/shortcut" would be added as a gesture action.

Made issue #113 for this

**Comment by TBog** [comment]
Added an `Show Android settings` option for gestures in commit 096d455dfc360bbf75ccead474977dbe20f2bb9a

**Comment by ltGuillaume** [comment]
But that's the same thing as Run app -> Settings, right?

**Comment by TBog** [comment]
> But that's the same thing as Run app -> Settings, right?

AFAICT that's right. Should I remove the option?

**Comment by ltGuillaume** [comment]
Since the list of options is already quite long and there's already a way of doing it via Run app, I think it doesn't have to be there per se, but whatever you like most.

**Comment by ltGuillaume** [comment]
I may have missed a commit, so unless you did change anything I'd say a miracle occurred: I just tested  it again by linking the action to "pull down from the left" and it just worked: the settings tiles are shown. I haven't received an update for Android since I last tested.
