### ISSUE TITLE
Button to the left of search bar doesn't work?

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#103]
# Description #

Whenever I tap the button (9 squares) button, the squares rotate, but nothing happens...
What is it supposed to do in TBLauncher?
- Should it show the favorites in the results list?
- In KISS it shows the favorites _inside the bar_.
- It could could show _all_ apps (I don't think there's a way to do this right now, which is rather annoying when assigning tags).

  * OS: Android 10
  * TinyBit Launcher version: preview build https://github.com/TBog/TBLauncher/issues/70#issuecomment-765472295

**Comment by TBog** [comment]
See #74

**Comment by TBog** [comment]
> - It could could show _all_ apps (I don't think there's a way to do this right now, which is rather annoying when assigning tags).

Have you tried the actions from the QuickList?
You can show all apps in A→Z or Z→A order.

**Comment by ltGuillaume** [comment]
> 
> 
> > * It could could show _all_ apps (I don't think there's a way to do this right now, which is rather annoying when assigning tags).
> 
> Have you tried the actions tab from the QuickList?
> You can show all apps in A→Z or Z→A order.

Oh damn, I totally forgot about those, because I eventually chose to use the QuickList solely for the tag filters. Sorry about that!

> This is a placeholder action. It will be possible to choose an action as is currently possible for the gestures.

I just compared with KISS Launcher, and one of the gesture actions is indeed to show all apps, kind of makes sense I'd say, especially with this icon 🙂

**Comment by TBog** [comment]
> Oh damn, I totally forgot about those, because I eventually chose to use the QuickList solely for the tag filters. Sorry about that!

Maybe we can add in the long touch popup of the app filter the two options for showing all apps

**Comment by ltGuillaume** [comment]
I think it's a strange place to put. However, I think giving the apps button (or whatever you want to call the button on the left) a long touch popup that includes all app filters plus the current reload action would be brilliant! The next step could be to be able to specify which of these actions would apply to a single tap on the button. I think this would make total sense for the end user and be more flexible.

**Comment by TBog** [comment]
Added customizable action for single tap on 9⃣⬜ button in commit a46c930151455f8895114d17740aa989c98772e4

**Comment by ltGuillaume** [comment]
Great! Can't wait to test it 😃
