### ISSUE TITLE
Tags in quick list sometimes require to be pressed twice

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#105]
# Description #

I have tags in the quick list. I could not find a real pattern in the behavior, but I often have to press twice in order to see the apps that have the tag, otherwise the list either remains or becomes empty.

## Steps to Reproduce ##

To reproduce the behavior:
1. Go to search
2. Click on a tag from the quick list
3. The results list may or may not show (I'm not sure if there were changes between https://github.com/TBog/TBLauncher/issues/70#issuecomment-765472295 and 5.4.contrast3, it seems to have improved?)
4. Press again
5. The results list will become empty if it was previously populated with the tag pressed in (2), otherwise it shows the tagged apps now
6. Press another tag in the quick list. The results list will just clear most of the times, instead of being repopulated with apps of the newly pressed tag.

## Expected behavior ##

Immediately populate the list upon first click on the tags. 

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: latest pre-release 5.4.contrast3

**Comment by TBog** [comment]
Does this still happen in [Release v6.0](https://github.com/TBog/TBLauncher/releases/tag/v6.0)?

**Comment by ltGuillaume** [comment]
Yes it does.

**Comment by TBog** [comment]
Can you please post the "Steps to Reproduce" on the v6.0 build?

**Comment by ltGuillaume** [comment]
It was still present in v6,but seems to be gone in the latest prerelease!
