### ISSUE TITLE
Remove gradient effect of scroll bar

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#106]
**Description**
TBLauncher looks a lot more modern since the latest UI changes, but a remnant of the old UI is the gradient of the scroll bar in the results list. It would be nice if the gradient were removed, the bar would be less wide and the color would be less prominent. I'm not sure which color setting it is using, perhaps a little transparency should do it. In fact, the scroll bar in the settings is already styled in such a way.

**Comment by TBog** [comment]
![Screenshot_20210129-075958_TinyBit launcher.jpg](https://user-images.githubusercontent.com/6465804/106237789-3269ff80-6208-11eb-913b-12d161dd30bd.jpg)

Are you talking about the left-right gradient?
What shape should the scrollbar have? A rectangle?

**Comment by ltGuillaume** [comment]
> Are you talking about the left-right gradient?

Yep

> What shape should the scrollbar have? A rectangle?

Yep. I don't know if it's OS dependent, but the preferences activity already has such a scroll bar with the desired properties (on my device)

**Comment by TBog** [comment]
fixed in commit f08727c519da50b2d2bed26e5eea60b3f97ca207
