### ISSUE TITLE
Add action/filter to show untagged items

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#107]
**Description**

It would be great to have an action or a filter "untagged" that shows all untagged items. This allows, for instance, to easily isolate all newly installed apps from the (tagged) regularly used ones. I think I would use that on a daily basis: test apps, have them listed under "untagged" easily, then if I want to keep them, I tag them appropriately. It sort of creates an "inbox" in line with the getting things done system.

KISS Launcher already sports such a menu item.

**Additional context**

It would be most intuitive to have this as a permanent filter, listed among the tag filters, but I guess it could be found alright among the actions, too.

**Comment by TBog** [comment]
fixed in commit 0ec71b9a8aadafec459d22ee6e09785711d076c2
