### ISSUE TITLE
Desktop Modes: cannot get back to widgets, doesn't respond

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#109]
# Description #

I'm not sure yet if I like the new behavior that keeps you in the search mode when pressing back (instead of going back to the widget mode from which I started the search mode), but if tap wallpaper to switch between the modes would work consistently, then I could get used to it. Unfortunately, it doesn't: 

## Steps to Reproduce ##

To reproduce the behavior:

1. Go from widgets mode into search mode (I do so by tapping the wallpaper)
2. Type something, then press back _twice_. Only the quick list will remain (why won't it go back to the widgets mode?) 
3. Press some (in my case _tag_) filters/actions on the quick list. It will stop showing items in the results list. 
4. The result is that I cannot go back to widgets mode by tapping the wallpaper. Actually, no gesture is working at that time. I've had the quick list items respond a few times, but currently they don't even open a results list anymore. Only the quick list popup shows up, other than that nothing works.

## Expected behavior ##

I'd say pressing the back key should first hide the keyboard. I don't think the search bar should also be hidden on the second press. Instead, the second time you press back, you should go back to the mode you came from. This is the original behavior. That being said, if you want to separate the modes more distinctly, I can get used to it if the gestures get fixed.

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: https://github.com/TBog/TBLauncher/releases/tag/v5.4-modes.1

**Comment by TBog** [comment]
In  `Features` -> `Gestures` -> `Tap empty screen` what is your setting?

**Comment by ltGuillaume** [comment]
It is, always has been.

**Comment by TBog** [comment]
Ok, I managed to replicate your problem. The result list is still visible even tho it's empty. You probably don't have a result list background to be able to see it.
When you say the gestures are not working it is because you're in fact touching the Result list.

As a workaround until it's fixed, when this happens, touch the border of the screen where there is no result list.

**Comment by ltGuillaume** [comment]
> Ok, I managed to replicate your problem. The result list is still visible even tho it's empty. You probably don't have a result list background to be able to see it.

That's right! I'll be sure to change some colors before reporting anything from now on!

> When you say the gestures are not working it is because you're in fact touching the Result list.

Makes total sense.

> As a workaround until it's fixed, when this happens, touch the border of the screen where there is no result list.

Cool. I've also change the Home button to switch between widgets and search, so that will now work, too.

**Comment by TBog** [comment]
fixed with commit d3e201db81d79368c0a8ef9713e1880baba67330 in PR #108

**Comment by ltGuillaume** [comment]
I'm afraid it would be very confusing for new users that the second time you press the back button, the launcher won't be returning to the previous desktop mode (widget/empty).
