### ISSUE TITLE
"Custom" quick lists

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#11]
I think that there should be quick lists for tags and that the icons for quick lists should be more customizable. 

Tags as quick lists would really help people find an app they need to use. If someone needs to go to a group video chat for work or a college class, they should be able to click the "Video Calling" tag and click on the app that they need to use instead of scrolling through an entire app list that probably wasn't sorted right. 

Customizable Quick list icons should also be a thing because I assume that there has to be an icon for a quick list button to be a quick list button. Also, I think that it feels good to be able to change the "apps" icon to something that matches your icon pack.

**Comment by TBog** [comment]
commit 2e2e83d181a4cb49c002b2d1dc3c3f6a0e56d082 adds custom icon and name to actions and filters

**Comment by HunterArmstrong** [comment]
That's good. Hope it works well.👍🏻🤞🏻

**Comment by HunterArmstrong** [comment]
Wasn't adding "Tags" to the quick list added in there as well? If so, I don't think I know how to do something like that.

**Comment by TBog** [comment]
I did not close this because I had no time to add the tags.
1. I need to add a tag management system (rename tags, tag icon or emoticon) first.
2. In the edit QuickList dialog, I need to make space for the tags. Either allow tags to be added to favorites from the tags management or eeplace the two grid lists with a tabbed view.

What do you think?

**Comment by HunterArmstrong** [comment]
> I did not close this because I had no time to add the tags.

Understandable

> 1. I need to add a tag management system (rename tags, tag icon or emoticon) first.

I think I have a couple ideas.

- Maybe a tag list feature in the settings. This way you can scroll through the list of tags you have in TB and do what you need from there. Like maybe delete a tag or add one to favorites with an icon.

- Maybe a quick setting in the right hand menu of the TB search bar saying "Add Tag To Quick List/Favorites". There, you can edit the icon yourself or use a default icon that's just a tag symbol.

> 2. In the edit QuickList dialog, I need to make space for the tags. Either allow tags to be added to favorites from the tags management or eeplace the two grid lists with a tabbed view.


Maybe a tabbed view would look a lot cleaner and simpler. You could probably add an "Add Tag" option to the tags tab that could lead to a setting where you could change the tag icon if you need to. I could be down for that.

**Comment by TBog** [comment]
fixed in 99d0d74dcfc28bbb8f1ae8100aa56031927839e5
Still needs testing, code and UI clean-up
Test build: [tags in QuickList build](https://github.com/TBog/TBLauncher/releases/tag/v4.6-dev.2)
