### ISSUE TITLE
[FR] show history

### ISSUE THREAD

**Issue by ildar** [TBog/TBLauncher#111]
In two more places :
1. Action list for gestures and alike
2. Instantly when Search Desktop appears (similar UX as in KISS)

**Comment by ltGuillaume** [comment]
For (2), see https://github.com/TBog/TBLauncher/issues/100

**Comment by ildar** [comment]
(1) is done & tested, thanks

**Comment by TBog** [comment]
fixed (2) in commit ce2b23e95725c70dab8ac19f49b4e416ca693ef1

**Comment by ltGuillaume** [comment]
I found a bit of a drawing issue with this: the search bar and keyboard open, then the history shows, but _then_ the quick list opens last, which makes the history items jump upwards. It would be best if search bar and quick list items were drawn before the result list is filled with the history items. Also, I see an animation when the quick list icons appear, but not with the history items.
