### ISSUE TITLE
Keyboard shown on top of search bar & quick list

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#115]
# Description #

Since v6 pre (possibly v5.4-modes.1) I regularly see my keyboard popping up on top of the search bar & quick list. Those two should of course jump to the top half of the screen, right above the keyboard.

![TBLauncher](https://user-images.githubusercontent.com/4777345/106943875-404ae380-6726-11eb-8ae3-ad4b6bc225d6.gif)

## Steps to Reproduce ##

To reproduce the behavior (as in GIF above):
1. Open search mode
2. Press back once
3. Tap the search bar and see what I mean.

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: 6.0

**Comment by TBog** [comment]
This does not happen on my device with Android 11. I'll try tomorrow on the emulator.

**Comment by ltGuillaume** [comment]
I just tried another keyboard app just to be sure it's not that,but I got the same results.

**Comment by TBog** [comment]
Workaround is to disable fullscreen in search mode

**Comment by ltGuillaume** [comment]
> 
> 
> Workaround is to disable fullscreen in search mode

Confirmed!

**Comment by TBog** [comment]
Is this fixed in [v6. 0-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.0-dev.1) ?

**Comment by ltGuillaume** [comment]
Yes! Just tested it by enabling fullscreen in search mode again, all fine now, thx!
