### ISSUE TITLE
Setting for desktop mode at start-up

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#117]
It would be nice if the user got a setting to specify in which desktop mode TBLauncher would start. Currently, it always starts in Empty mode.

It's not a big deal at first start (although possibly confusing for new users), but when Android kicks TBLauncher out of memory, it might again start in the Empty mode instead of the expected mode.

**Comment by ltGuillaume** [comment]
Over the last days, Android kicked TBLauncher from memory about 5 times, so I could see what would happen. As expected, it restarts in Empty mode. So an option as proposed would indeed also be beneficial for these cases.

**Comment by TBog** [comment]
fixed in commit 7f19aa250f410458f66417fbd5dbf8d8424dacd9

**Comment by ltGuillaume** [comment]
Yesss, perfect!
