### ISSUE TITLE
Text of popup in settings (and status bar) unreadable

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#123]
# Description #

We can barely read the text in the popup to change themes anymore. Below are screenshots. **Also notice that the status bar has white icons on white background in the white theme** and the white borders of the popup in the 8bit theme.

### Screenshots ###

![Screenshot_20210222-144406_TinyBit_launcher](https://user-images.githubusercontent.com/4777345/108717397-87561880-751d-11eb-954c-c36519a3d975.png)
![Screenshot_20210222-144421_TinyBit_launcher](https://user-images.githubusercontent.com/4777345/108717400-87561880-751d-11eb-844a-e43d5739de85.png)
![Screenshot_20210222-144428_TinyBit_launcher](https://user-images.githubusercontent.com/4777345/108717401-87eeaf00-751d-11eb-820e-8d1ced182301.png)
![Screenshot_20210222-144451_TinyBit_launcher](https://user-images.githubusercontent.com/4777345/108717403-87eeaf00-751d-11eb-90eb-cbd76e0ad629.png)
![Screenshot_20210222-144503_TinyBit_launcher](https://user-images.githubusercontent.com/4777345/108717405-88874580-751d-11eb-8540-d9a570c5bf1f.png)

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: 6dev4

**Comment by TBog** [comment]
fixed in commit d618299300fb650e85262bf285e23c42309155e6

**Comment by ltGuillaume** [comment]
It's not completely fixed, see

>Also notice that the status bar has white icons on white background in the white theme

**Comment by TBog** [comment]
> Also notice that the status bar has white icons on white background in the white theme.

The status bar is always the same color as the notification bar. In your case it's transparent.

**Comment by TBog** [comment]
does commit 11830f8bad71532d45dbae705a621f0fdfd1b14c fix the status bar white icons on white background?

**Comment by ltGuillaume** [comment]
Could well be, I don't have an Android Studio setup right now, so I'll have to wait for a new build 🙈

**Comment by ltGuillaume** [comment]
Fixed in 6.1dev.1!
