### ISSUE TITLE
Subicons show up on shortcuts

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#13]
I don't really need to see a subicons on a shortcut. If that is what helps separate shortcuts, then that's what tags are for.

**Comment by TBog** [comment]
Great idea. I'll add a preference for hiding the badge.
Should this be a global preference or a toggle for each shortcut?

**Comment by HunterArmstrong** [comment]
Global.

**Comment by TBog** [comment]
fixed in 83b972697e190d3aed17d9fe48da08e817f8389a
