### ISSUE TITLE
At a Glance widget does not work on Pixel 3a XL with Android 11

### ISSUE THREAD

**Issue by ebirtaid** [TBog/TBLauncher#130]
# Description #

When attempting to add the at a glance widget from google, the widget is not added and the default launcher setting is lost.
## Steps to Reproduce ##

To reproduce the behavior:
1. Go to the widget screen.
2. Tap add widget
3. Select at a glance
4. Widget is not added. Pressing home will bring me to the pixel launcher and I need to go to settings to select tinybit.

## Expected behavior ##

I expected the widget to be added.
## Device info ##

  * Device: Pixel 3a XL
  * OS: Android 11
  * TinyBit Launcher version: 6.1

**Comment by TBog** [comment]
From your description it seems like the launcher is crashing. Could you please post the callstack?
The widgets have not been tested on Android 11. I'll try on the emulator but it may not reproduce without the widget you said

**Comment by ebirtaid** [comment]
[logcat_03-02-2021_15-09-44.txt](https://github.com/TBog/TBLauncher/files/6071503/logcat_03-02-2021_15-09-44.txt)

**Comment by TBog** [comment]
`java.lang.SecurityException: Permission Denial: starting Intent`
I think there is a permission missing.
I can easily fix the crash but I'll have to research the permissions.

**Comment by TBog** [comment]
fixed in version 6.2
