### ISSUE TITLE
Make indexing contacts optional

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#131]
**Description**

I think some people may want to have the option to not index their contacts.

**Solution**

Contacts can be an optional provider in the settings.

**Alternative solutions**

I'm using XPrivacyLUA, so I can block contact search that way just fine.

**Comment by TBog** [comment]
If you remove the contacts permission no "indexing" will happen. What Android version does not have this option?

**Comment by ltGuillaume** [comment]
Ihave absolutely no idea why I forgot this. I just saw my contacts listed again after an XPrivacyLUA updated caused issues, and apparently I gave TBLauncher the contacts permission. My mistake, sorry!
