### ISSUE TITLE
double tap to sleep

### ISSUE THREAD

**Issue by lichingyun** [TBog/TBLauncher#138]
Hello, I suggest to add the gesture "double tap to lock screen" like in olauncher.
Is good to lock the screen without using the phisical button of the phone

Thanks for this beautiful launcher

**Comment by TBog** [comment]
On my device the lock screen I implemented doesn't do the same as the power button press.

Could you please have a look and let me know if the current implementation is what you're looking for?

**Comment by lichingyun** [comment]
yes tell me how can I help you.
I use a Xiaomi Whyred redmi note5 with ArrowOs android 11

**Comment by TBog** [comment]
test build can be found [here](https://github.com/TBog/TBLauncher/releases/tag/v6.1-feature.1)

**Comment by lichingyun** [comment]
> test build can be found [here](https://github.com/TBog/TBLauncher/releases/tag/v6.1-feature.1)

hello Tbog I have nearly installed this test build, all is ok the "double tap to sleep" works very well, many thanks.
Personally I think you can release a new updated build in Fdroid

**Comment by lichingyun** [comment]
in the test build I cannot find the "notification dot" for app like telegram/ whatsapp/ email...

**Comment by TBog** [comment]
The notification dot is not implemented afaik. Did it ever work?

**Comment by TBog** [comment]
> and how to "hide" the contact name from the search bar?

I'm not sure what you mean.
* The QuickList has show names preference.
* If you don't want contacts to show in the results list you can remove the permission

**Comment by ltGuillaume** [comment]
> 
> 
> > and how to "hide" the contact name from the search bar?
> 
> I'm not sure what you mean.
> 
>     * The QuickList has show names preference.
> 
>     * If you don't want contacts to show in the results list you can remove the permission

@lichingyun
...and if you don't mean that, but the actual text _"Search in apps, contacts, ..."_ that's in the search bar by default, check TBLauncher's settings, then `Features`, then `Edit search hint`.

**Comment by lichingyun** [comment]
> The notification dot is not implemented afaik. Did it ever work?

yes, in the build from Fdroid the notification work, I use a Xiaomi redmi note5 whyred with android 11 (arrowOs)

**Comment by lichingyun** [comment]
> * If you don't want contacts to show in the results list you can remove the permission
Thanks, is the permission
