### ISSUE TITLE
Failure to use a search engine or calculator on TinyBit

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#14]
I liked how I could look up something from a search engine or use a calculator on KISS. I wish I could use it on TB.

**Comment by TBog** [comment]
I'm not sure about this. 
The calculator would be better as a widget with all the math symbols. 
The web search can also be made with a widget.
I will think about it and when I have fixed the other issues will make a prototype.

**Comment by HunterArmstrong** [comment]
I'll let you think about it some more. That was just what I was used to when it came to KISS. it just felt easier. Y'know

**Comment by daffydock** [comment]
Fair. Well, I definitely hope that you do. That's the only thing that seems missing from making this superior to KISS, hands down.

**Comment by HunterArmstrong** [comment]
Yeah. But there are still some issues right now.

**Comment by TBog** [comment]
fixed

test build can be found [here](https://github.com/TBog/TBLauncher/releases/tag/v4.6-dev.3) on the [Releases](https://github.com/TBog/TBLauncher/releases) page
