### ISSUE TITLE
Feature: Change Launcher Icon

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#140]
**Description**

Thought this would a nice feature to have after the launcher button behavior setting was added

**Solution**

Maybe change the launcher icon to an icon from your Icon pack. This may take away the animation effect when you tap on the icon, though.

**Comment by TBog** [comment]
This could be generalized.
We should allow users to change any hard coded icon by long-touching it and selecting `Custom icon... `

**Comment by TBog** [comment]
Only the "Launcher icon" remains unchanged

**Comment by TBog** [comment]
Ok, I think this issue is resolved.
