### ISSUE TITLE
Fullscreen doesn't work in Search mode

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#141]
## Steps to Reproduce ##

To reproduce the behavior:
1. Go to Behavior -> Desktop mode Search
2. Enable Fullscreen
3. The status bar will still show in Search mode

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: 6.2 Replace AsyncTask

**Comment by TBog** [comment]
It works as long as the keyboard is hidden.
As far as I can tell it's an Android restriction.

**Comment by ltGuillaume** [comment]
> It works as long as the keyboard is hidden.

Ah yes, and only if you disable "Close keyboard same as back button", then hide the keyboard with the back button. It won't work if you close the keyboard by another way, e.g. by scrolling.

**Comment by TBog** [comment]
I'll have a look at closing the keyboard when you scroll the result list and fix the fullscreen is possible

**Comment by ltGuillaume** [comment]
It's a minor thing, and since it's simply impossible with the keyboard showing anyway, you could also just remove the Fullscreen option for the Search mode, easy peasy.
