### ISSUE TITLE
[FR] tags list

### ISSUE THREAD

**Issue by ildar** [TBog/TBLauncher#142]
... as a Behavior action.
I want the Launcher button to show the list of tags. Tap on one would show the associated items.
IMPORTANT: sorting should be fixed, preferably manually sorted. 
Thanks!

**Comment by ltGuillaume** [comment]
+1!

**Comment by ildar** [comment]
@TBog, still dodn't think about this one?
sorry for ETA.

**Comment by TBog** [comment]
There is the tags manager. I'll have to add some functionality and it should work.

**Comment by ildar** [comment]
em, the question is about the tag list (similar to KISS's), hope you mean
exactly that.
I'm thrilled to test it.

**Comment by ildar** [comment]
This is insanely awesome!
launching TEST sequence )))

**Comment by TBog** [comment]
Thank you.
There was one issue already found with the tags menu. The result list can open on top of the widgets.
