### ISSUE TITLE
To fix keyboard and searchbar

### ISSUE THREAD

**Issue by lichingyun** [TBog/TBLauncher#153]
**Description**
This is my TBLauncher screenshot, I really like it.
Is possible to fix the keyboard and the searchbar like in the picture?
I don't want they disappear when I touch some of the button
 
![Screenshot_20210417-111655](https://user-images.githubusercontent.com/79099214/115110526-27f41200-9f7c-11eb-96c5-fbc494dcb9c9.png)

**Solution**
Maybe in the settings is possible to add something like "fix the keyboard" or "show keyboard at the start" like in Kiss Launcher

Many Thanks

**Comment by TBog** [comment]
What button did you touch to make the keyboard dissappear?

Try setting 
1. `Behavior`->`Keyboard`->`Link keyboard to search bar visibility` to get the keyboard to show every time you to into the Search desktop 
2. `Behavior`->`Gestures`->`Tap empty screen` set to `Show "Search" desktop` in order to always stay in the Search desktop.

**Comment by lichingyun** [comment]
Hello Tbog, I follow your advice.
The keyboard disappearif I press the "back" button, in the screenshot is the button at the bottom right (the triangle)

**Comment by TBog** [comment]
The back button might still change the desktop, if so look into the `Behavior`->`Behavior`->`Desktop mode "Search"`->`Back button` and change the behavior.

**Comment by lichingyun** [comment]
thanks I try when I come back home

**Comment by lichingyun** [comment]
> The back button might still change the desktop, if so look into the `Behavior`->`Behavior`->`Desktop mode "Search"`->`Back button` and change the behavior.

Tbog I have look all the settings in Behavior/Behavior but the Keyboard always desappear when I press the back button.
I forget to say I am using Gboard

**Comment by TBog** [comment]
I'll have a look at the code and figure out a solution for you to keep the keyboard open when you press the back button (🔽)

**Comment by lichingyun** [comment]
Wow! Many thanks 😊🙏

**Comment by TBog** [comment]
here is a build with my fix: [v6.4-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.4-dev.1)

**Comment by ltGuillaume** [comment]
> here is a build with my fix: [v6.4-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.4-dev.1)

Can't update to that version from v6.4 (version code is lower).

**Comment by TBog** [comment]
It's not an upgraded version, I'm lazy and haven't made a github action to generate new versions when building.
If you don't mind **loosing all the shortcuts you have**, you can backup all and uninstall the version you have then install the test version and restore the settings from the backup.

**Comment by lichingyun** [comment]
> It's not an upgraded version, I'm lazy and haven't made a github action to generate new versions when building.
> If you _don't mind_ **loosing all the shortcuts you have**, you can backup all feature then uninstall the version you have then install the test version and restore the settings from the backup.

Thanks Tbog, this works perfectly 🙏

**Comment by ltGuillaume** [comment]
> It's not an upgraded version, I'm lazy and haven't made a github action to generate new versions when building.
> If you _don't mind_ **loosing all the shortcuts you have**, you can backup all feature then uninstall the version you have then install the test version and restore the settings from the backup.

I'll wait for the next build then 😅

**Comment by lichingyun** [comment]
Thanks Tbog
