### ISSUE TITLE
Wallpaper please?

### ISSUE THREAD

**Issue by jvschiavo** [TBog/TBLauncher#156]
Could you please provide the wallpaper shown at F-Droid?

![Screenshot_20210423-005226](https://user-images.githubusercontent.com/20977075/115816268-f2fa1c00-a3ce-11eb-9fa5-db29b7558763.png)

**Comment by TBog** [comment]
here is a reverse image search result: https://pbs.twimg.com/media/EUb_oXHU4AAXFxk.jpg
I'm not sure of my original source as I have my wallpaper change every hour using [Muzei](https://muzei.co/) with images from [Vitrina](https://play.google.com/store/apps/details?id=stoyck.vitrina&hl=en&gl=US)
Images come from:
* [AnimePhoneWallpapers](https://www.reddit.com/r/AnimePhoneWallpapers/)
* [AnimeWallpaper](https://www.reddit.com/r/AnimeWallpaper/)
* [streetmoe](https://www.reddit.com/r/streetmoe/)

**Comment by jvschiavo** [comment]
Thank you very much! :)
