### ISSUE TITLE
Option to add Folders or/and Apps to the Quick List

### ISSUE THREAD

**Issue by bigbavarian** [TBog/TBLauncher#165]
I wish there where some option to add individual folders and apps you always need to use esay to the Quick List. For now i go the way over the favorites and i have to swipe them frome fav to the QL. But i also wanna use the Fav. Now i have them 2 times. Thats not so good.

Thanks

**Comment by TBog** [comment]
You can use tags instead of folders.

- Tags can be added to the QuickList.
- Apps can be added to the QuickList, first add it to favorites, then add it to the QuickList

**Comment by bigbavarian** [comment]
Thats the way. Thanks a lot. I dont become that idea.
