### ISSUE TITLE
Drawer/Applist/Menu should give me the option to show list or grid

### ISSUE THREAD

**Issue by bigbavarian** [TBog/TBLauncher#166]
In my opinion a drawer should give you the opportunity to choose between different views. I dont like lists that mutch and i wanna like more possibility to change that. 3x6 4x5 and more....

Thanks

**Comment by TBog** [comment]
I personally use a widget for that purpose.

The grid view for the apps is my the TODO list but I was hoping to get the list view bug-free before working on other features.

**Comment by TBog** [comment]
Is the number of rows important to you? Or can I just show as many rows as possible?
