### ISSUE TITLE
Option to not show contacts

### ISSUE THREAD

**Issue by yetanotherfossman** [TBog/TBLauncher#169]
**Description**

This is a very good launcher, with a lot of good features. However, I don't see a basic one: I can't deactive suggestions for my contacts when I use the search bar.

**Solution**

An option in settings for not show contacts in the results, just like KISS does.

**Alternative solutions**

`¯\_(ツ)_/¯`

**Additional context**

Some people don't like their contacts being showed in the homepage. That.

**Comment by TBog** [comment]
Deny contacts permission.

**Comment by yetanotherfossman** [comment]
Yeah, non-rooted Lollipop here.

**Comment by daffydock** [comment]
@yetanotherfossman You don't need root to deny it this permission. Go into your app's settings.

**Comment by ltGuillaume** [comment]
I think this might not be implemented into Android 5 Lollipop yet.
