### ISSUE TITLE
Launcher crashes whenever an app is excluded.

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#17]
Already discussed. But still worth mentioning again.

**Comment by HunterArmstrong** [comment]
@TBog 

Are the crashes easy to fix?

**Comment by TBog** [comment]
Quick fix is to remove the button.

**Comment by HunterArmstrong** [comment]
> Quick fix is to remove the button. 

Wdym?

**Comment by TBog** [comment]
> > Quick fix is to remove the button. 
> 
> Wdym?
> 

I mean the exclude button. 
This feature is not currently working anymore. I need to hide the excluded apps from the filters and figure if we can have both a hidden and favorite app.
Also figure how to show the excluded apps, maybe a password or in the preferences or both.

**Comment by HunterArmstrong** [comment]
> > > Quick fix is to remove the button. 
> > 
> > Wdym?
> > 
> 
> I mean the exclude button. 
> I need to hide the excluded apps from the filters and figure if we can have both a hidden and favorite app. Also figure how to show the excluded apps, maybe a password or in the preferences or both. 

This may be dumb. But, what about having the term "Favorite" as a default tag in TB that can potentially be used in the quick lists. Then, have an option in the settings to view and exclude apps from TB? That way you don't have to use an exclude button in the home screen and pull up favorites.

**Comment by TBog** [comment]
fixed in f9621b95f6bda4a7755d266796c1eaefe2dc3816

**Comment by HunterArmstrong** [comment]
> This feature is not currently working anymore. I need to hide the excluded apps from the filters, ... figure if we can have both a hidden and favorite app,... And figure how to show the excluded apps, maybe a password or in the preferences or both. 

I think that this issue should be reopened. We have already discussed that this is what should be done in order to get the exclude button in at least some working shape.
