### ISSUE TITLE
Search gets cleared by a result list refresh

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#172]
# Description #

Since the releases _after_ v6.4 final ("widget pages" and I think also "dev.1"), TBLauncher _always_ gets kicked out of memory on my phone. This is far less the case with 6.4 final.

As a result, every time I press the Home button to see the Search mode, everything gets reloaded.

As soon as I have the possibility to type in the search bar, I type a few characters... and then the result list refreshes (now showing the recently run items) _and the characters I typed are gone_.

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: v6.4 - widget pages

**Comment by ltGuillaume** [comment]
I just found out that this also happens in v6.4 final. Can't say I remember ever seeing it in 6.3.x

**Comment by TBog** [comment]
Interesting observation. I'll see what I can do.
I have a feature in progress (upgrade `List View` to `Recycle View`) that I'm currently working on and may include the fix there.

**Comment by ltGuillaume** [comment]
Sounds good, I'll report back as soon as there's a (test) release! 🙂

**Comment by TBog** [comment]
Should be fixed with commit 63b7e5815c3a991ebdf037e0ddc3597103b14978
You can test it in the release <a href='https://github.com/TBog/TBLauncher/releases/tag/v6.6-dev.2'>Update v6.6 - dev.2</a>
