### ISSUE TITLE
[Feature Request] Add possibility to disable icon color modulation for contacts pictures 

### ISSUE THREAD

**Issue by HeiWiper** [TBog/TBLauncher#181]
**Description**
I love the icon modulation feature and I've been using it with monochrome icon packs to match the icon color with the launcher color, but there's an issue which is when the contacts pictures are also modulated.
I don't think it is necessary to modulate the color of contacts pictures as it really becomes impossible to recognize them, that's still only my use case as I only change the hue or colors values.

**Solution**
Either disable icon modulation for contacts or add a toggle to disable it.

**Alternative solutions**
Not directly related to the same problem but I would love if I could disable icon modulation for some icons, I usually try to pick an icon from the icon pack for apps that aren't supported yet. but sometimes there are apps that I would just leave their original icon and the icon modulation kinda messes all their colors when changing the hue value.

**Additional context**
Here in this screenshot I modulated the icon colors which were originally white to have a purple/pink color. As you can see, the contact picture colors are messed up, that picture is the same one in my Github.
![Screenshot_20210724-154201_TinyBit_launcher](https://user-images.githubusercontent.com/12894695/126871996-f43331ef-0e57-4a32-8086-57adf9cba081.png)

**Comment by TBog** [comment]
I can do the toggle relatively fast. I think I'll do just that for now.

What I envisioned was a per-icon modulation option, but I had some UI problems.

I probably would have to change how custom icons are stored in the DB.
