### ISSUE TITLE
Change Search bar size and text size separately

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#182]
**Description**
I want to be able to change the search bar size but not the text size alongside with it.

**Solution**
Two separate settings; one for search bar size. One for text size.

**Comment by TBog** [comment]
I had them based on a single size / slider because the text gets clipped if you set a large text and a small bar. I think it's a bad UX when text gets clipped.
Why do you need this? Can you show an image with the problem?

**Comment by ltGuillaume** [comment]
Perhaps you can add a setting to set the text size in percentages then?

**Comment by Invisible3ck** [comment]
@TBog Perhaps you could add a warning regarding this issue? "Warning: Setting a large text size and a small search bar size can result in clipped text."

**Comment by TBog** [comment]
I understand your frustration. The problem I see is that without having a preview for this setting you'll have to go back and forth to set the right size.

I implemented a preview for the color filter (icon hue and saturation). I think I can do something similar for the search text.

**Comment by TBog** [comment]
Can we close this?
