### ISSUE TITLE
Pixel Pill-like search bar

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#194]
**Description**
I think that there should be a pixel pill search bar for TB launcher. I think that it would look cool and sort of minimalist. You could probably have the time and the weather on there too.

![20QBQLB5bP4sAelpIWqNoXJlwU9yd_ESNdIoYUG0KeKdJMOmo5AozIF2Ijr8OoZ0Rypv=h900.png](https://user-images.githubusercontent.com/57189836/131715272-dd33f7ef-cde9-4bf7-a21b-c32b3ed39f5a.png)

**Comment by TBog** [comment]
I like how it looks.
The weather would need internet permission, that I can't do. But maybe we can squeeze a widget there.

**Comment by HunterArmstrong** [comment]
Cool beans!! Maybe a "Pill Color" and a "Pill icon" setting as well?

Also, can you add the clock and date if that is possible?

**Comment by TBog** [comment]
Date and clock are very much possible.
I'll have to add options for color and size for all.

The amount of options has grown, I think we need to have some presets. Both for colors and for features.

**Comment by HunterArmstrong** [comment]
Of course! Whatever makes it work well.

**Comment by TBog** [comment]
Can you please expand on this?
Would the pill transform in a text box when the keyboard opens?
Should the search pill stay above the dock?

**Comment by daffydock** [comment]
If I may add 0.2 cents, the pill should either stay at the bottom where the search bar is now, or have the option for top/bottom. One of the great things about Tinybit is that you can do quite a _bit_  with just one hand. Search, call, email, etc. Having the pill as per other launchers, that is, usually at the top makes for a lesser user experience if people need to strech their hand or use two to reach out, to have it transform.

Granted, you could also have it expand when the keyboard opens, for a smoother experience, albeit I would be biased towards having it at the bottom. I do wonder what would the point be of having 2 search bars? It would seem that it makes more sense to just replace one for the other. 

Wonder what will @HunterArmstrong say.

**Comment by TBog** [comment]
please leave feedback on the PR
