### ISSUE TITLE
Feature: Selected quick list icon background color

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#20]
Whenever an icon from the quick list is selected the background shifts to a color that seemed a little off from the selected quick list color. I just felt like that color should be customizable as well.

**Comment by TBog** [comment]
The problem I have right now is setting the ripple color, once I figure that out I'll also set that color for the filter toggle.

**Comment by HunterArmstrong** [comment]
Okay. I think what you have right now is good, though.

**Comment by ltGuillaume** [comment]
On a similar note, it seems you can't change the light-green highlighting color when selecting an item at all, am I right? I'd very much like to be able to change that color (and the light-green background color of the settings, which imho doesn't look professional at all).

**Comment by TBog** [comment]
> it seems you can't change the light-green highlighting color when selecting an item at all

It's what I was talking about, the ripple color.
Once I find a clean way to set that color I'll close this issue.

---

>  the light-green background color of the settings, which imho doesn't look professional at all

I had some problems figuring out how to change the color of the list separator (or list divider) and that is why I had to use a light background for the settings. Can't use white because some colors by default are white and the preview does not have a border.
I'll change the colors from the settings activity eventually. Please open a separate issue about this and maybe give an example of how you'd like it to look.

**Comment by ltGuillaume** [comment]
> > it seems you can't change the light-green highlighting color when selecting an item at all
> 
> It's what I was talking about, the ripple color.
> Once I find a clean way to set that color I'll close this issue.

Aah got it, sorry. I was confused by the fact that I don't see a ripple, just that the entire background of the item changes color.

> > the light-green background color of the settings, which imho doesn't look professional at all
> 
> I had some problems figuring out how to change the color of the list separator (or list divider) and that is why I had to use a light background for the settings. Can't use white because some colors by default are white and the preview does not have a border.
> I'll change the colors from the settings activity eventually. Please open a separate issue about this and maybe give an example of how you'd like it to look.

That makes sense, will do.

**Comment by TBog** [comment]
> Aah got it, sorry. I was confused by the fact that I don't see a ripple, just that the entire background of the item changes color.

I think you're talking about the `Quick-List` > `Toggle background color`. That one can be found in the settings and can be changed.

**Comment by ltGuillaume** [comment]
Nope, but now I double-checked, I do see that the ripple, sorry. I did mean the items in the result list, not the quick list.
