### ISSUE TITLE
Outdated screenshots 

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#202]
# Description #
The preview screens on the stores and on GitHub are outdated 

## Context ##
The app looks different now. The preview screens do not show the current feature set. 

## Steps to Reproduce ##
To reproduce the behavior:
1. Go to GitHub or store page
2. Scroll to preview images 
3. See images from older version

## Expected behavior ##
Images should depict latest design.

**Comment by suman-somu** [comment]
hey, 
i just looked into this and i can fix this . 

so , with my request to you i am working on this .

**Comment by TBog** [comment]
Sounds great. I'm looking forward to reviewing the pull request

**Comment by suman-somu** [comment]
#203 done the pull request 

ready to adjust anything if not done something accordingly 

please review and merge .

**Comment by suman-somu** [comment]
#203 done the pull request .

please review it and merge .

**Comment by TBog** [comment]
fixed by #203
