### ISSUE TITLE
Handle "Untagged" as a regular label item

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#222]
1. Add "Untagged" to **Tags to show**and **Tags order** dialog
1. Show "Untagged" in **Tags menu as results**
1. Allow **setting** an icon for "Untagged" in Tag manager
1. Allow **renaming** the tag in Tag manager

**Comment by TBog** [comment]
1. You can toggle on the **Show untagged** preference, it's always going to be the last option of the menu
2. Sure
3. Why in the Tag manager?
4. Can't you already do this? Please explain what your expected steps are.

**Comment by ltGuillaume** [comment]
> 1. You can toggle on the **Show untagged** preference, it's always going to be the last option of the menu
> 3. Why in the Tag manager?

Because it would be far more consistent and intuitive to handle the bahavior of "Untagged" like that. It would allow changing the icon, name and order for "Untagged" just like a regular "menu item" among the other tags.

>     4. Can't you already do this? Please explain what your expected steps are.

I meant renaming "Untagged".

**Comment by TBog** [comment]
How would you differentiate between a tag and "untagged"?

**Comment by ltGuillaume** [comment]
For the end user? Something like this?
![tag-manager](https://user-images.githubusercontent.com/4777345/143498808-c62f0be4-e3e9-4931-830f-753a4dd3abe8.png)
