### ISSUE TITLE
Don't open keyboard when showing tags or tags menu as results

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#231]
When opening a tag in the results list, the keyboard is also opened (with "Link keybaord to seach bar visibility). I don't think this makes sense, because the search field isn't filtered to the tag anyway. It would make more sense to use that part of the screen to show as much of the list as possible.

The same goes for the "(reversed) tags menu as results".

**Comment by victor0d** [comment]
Hi Guillaume,
Only for the sake of the discussion, and maybe brainstorming too.
- I agree that dismissing the keyboard, as you describe, is more convenient. But at the same time, (thinking from the code point of view too), adding exceptions to **\<Link keyboard to search bar visibility\> = 1 (ON)** could create confusion and likely bugs.
- My suggestion (for a similar behaviour, although it will not be exactly the same) would be keeping **\<Link keyboard to search bar visibility\> = 0 (OFF)** and adding a new action (to be used with gestures) that do: **Open_Keyboard+Go_To_Search_Desktop**
This way, a gesture will go to Search_Desktop while opening the keyboard; but there will still be options to go to the Search_Desktop with a dismissed keyboard (including tag opening), and the possibility to dismiss the keyboard from within the Search_Desktop when required.

Just a thought.

**Comment by ltGuillaume** [comment]
That's a good point!
