### ISSUE TITLE
App not installed when installing the apk

### ISSUE THREAD

**Issue by kurkii** [TBog/TBLauncher#234]
# Description #
"App not installed" error when attempting to install TBLauncher from F-Droid or from the apk under the Releases tab

## Steps to Reproduce ##
1. Download apk
2. Click on it, click install
3. Get error

## Expected behavior ##
The app would install without any error message

### Screenshots ###
![Screenshot_20220122-121547](https://user-images.githubusercontent.com/95172106/150636478-7ddbcbfe-bf9a-4e03-a987-0ddadf94b400.png)

## Device info ##

  * Device: Google Pixel 3a
  * OS: Android 12
  * TinyBit Launcher version: v6.8

**Comment by kurkii** [comment]
Update: I have installed v6.7 sucessfully, unsure why v6.8 does not want to install.

**Comment by TBog** [comment]
I just upgraded my Samsung phone to Android 12. I'll test the v6.8 release apk this weekend.

**Comment by TBog** [comment]
Fixed in release [v6.9](https://github.com/TBog/TBLauncher/releases/tag/v6.9)
