### ISSUE TITLE
Back key in Search_Desktop is applied twice

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#238]
Hi TBog,

Sorry for reporting so many issues these days. The more I play with the launcher the more I like it. Thanks. But I also find issues.

It seems that "Back" key/press in Search_Desktop is applied twice. Let me show you the following video:

\#\#\# Settings are set as:

\<Link keyboard to search bar visibility\> = 0 (OFF)
\<"Back" action when closing keyboard\> = 0 (OFF)

"Search Desktop" \<Back Button\> = "Show \<\<Widgets\>\> Desktop"
"Widgets Desktop" \<Back Button\> = "Show Notification Panel" (chosen only to make the bug behaviour easily visible, but the same result can be achieved with other options)

\#\#\#

1) When the keyboard is dismissed:
- Pressing "Back" will go Widgets_Desktop and apply a second "Back" showing the Notification_Panel

2) When the keyboard is active:
- Pressing "Keyboard_Dismiss" dismisses the keyboard and apply a second "Back" and goes to Widgets_Desktop.

\#\#\#

PS: Full interface configuration attached as well

Device: Oneplus6
OS: CRDroid6.23(Android10) GApps-less
TBLauncher: 6.8

https://user-images.githubusercontent.com/90806717/150830782-1195b952-ca61-42d7-bcab-0c3e4bd128cb.mp4

[interface.xml.zip](https://github.com/TBog/TBLauncher/files/7927413/interface.xml.zip)

**Comment by victor0d** [comment]
Excellent !!!!
Shall I keep the record opened to avoid being reported again until the commit get merged, or do you prefer to close it now ?
Thanks

**Comment by TBog** [comment]
I'm not sure the fix is proper yet. I'm still testing different configurations and comparing with previous version.
I'm thinking I should maybe change the preferences because some configurations are un-intuitive.

**Comment by victor0d** [comment]
Yes, it is true that the amount of flexibility in the launcher is amazing. But it also can lead to complex combinations (as you say, some times counterintuitive)

**Comment by victor0d** [comment]
I had been looking into some of the closed issues of the launcher, and https://github.com/TBog/TBLauncher/issues/153 called my attention because there seem to be a request to NOT close the keyboard when (back/dismiss) is pressed.

I am not sure if I am missing something, but it seems counterintuitive to me.
And it maybe related to these issues.

**Comment by victor0d** [comment]
WORKING !!!!

**Comment by ltGuillaume** [comment]
I don't think this is fixed properly:

- Enable `"Back" action when closing keyboard"` on a Samsung S5, Android 10: the keyboard is closes with the Back button, but it does NOT trigger the "Back" action.
- Disable `"Back" action when closing keyboard"` on a Nokia 3, Android 9: the keyboard doesn't even close, i.e. the Back button is blocked completely. (Enabling the option _does_ trigger the "Back" action on this device.)
