### ISSUE TITLE
Multiple Tags/Name Search

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#240]
Currently the fuzzy search is executed against one-tag or the app-name. It would be nice to execute 2 or 3 queries (likely 2 is enough) using space as separator (obviously the space is ignored in a single search due to the fuzzy search).

This way, we could match into more than one-tag and app-name. Matching things like:
Search: "s s" . . . . could match . . . App: "**s**shd.sh" . . . . . . . . . . . . Tags: "**S**cript"
Search: "s b" . . . . could match . . . App: "**b**ackup.sh" . . . . . . . . . . Tags: "**S**cript"
Search: "c a s" . . . could match . . . Shortcut: "**A**ndrew **S**mith" . . . Tags: "**C**ontacts"
Search: "h b b" . . . could match . . . App: "**B**romite" . . . . . . . . . . . Tags: "**h**ttp" "**b**rowser"

Just for discussion, and again, I believe 2 searches would be enough.

**Comment by TBog** [comment]
This preference might be called "Split search words"
Each word ("h b b" would have 3 words) would be matched using the current search system.
The only problem I see is how I can generate a result score from 3 independent words as I'm not sure adding the score of the 3 searches is good enough.
Your example
Search: "c a s" . . . could match . . . Shortcut: "**A**ndrew **S**mith" . . . Tags: "**C**ontacts"
is not taking into account that the word "Contacts" contains all three letters "c a s"

**Comment by victor0d** [comment]
I agree that 3 searches maybe too much.
Keeping it in 2 searches should be enough. This way matching AppName+Tag or Tag+Tag. In this case the first space will be the separator. Any other spaces from the search line either in the second search or ignored (up to you). 

I don' think adding the independent searches would be good because that is an OR addition, and it should be a AND addition. So, any result should be positive in both searches.

The problem I see is how to avoid the 2 independent searches matching the same Tag/Name as you suggested in your last sentence.

**Comment by TBog** [comment]
I think this is a better solution than #89

**Comment by victor0d** [comment]
I didn't quite understand the request in https://github.com/TBog/TBLauncher/issues/89. I wasn't completely sure at the beginning of the text, and at the end, I though it is referring to a command that launches the browser with a search, which in my opinion it is a bit redundant when it happens automatically when there are no matches (besides the screenshot seems missing).

Going back to my original proposal, I was thinking that maybe it is not very difficult with a SQL command against the SQLite table. I am not an expert in SQL but I am going to take a look.

**Comment by TBog** [comment]
> Going back to my original proposal, I was thinking that maybe it is not very difficult with a SQL command against the SQLite table. I am not an expert in SQL but I am going to take a look.

Fuzzy search can't work with SQL. Maybe I don't understand what you wanted to do with SQL.

**Comment by victor0d** [comment]
You are very right. I have been taking a look and there are some small functions proposed by some users but I don't think they fit for these case and this code.

I had a quick look to the code and I think what you were suggesting makes much more sense: two queries that need to added (multiplied actually: ANDed). But it is still not as simple as my first thought.

I need to look into the code further, before I write any nonsense.

**Comment by victor0d** [comment]
What about this:
- Executing a regular search
- As soon as there is a "space" the rest of the line is used to execute a search on the previous results.

Obviously the second search may match on the same tag/name as the first search. This will give us some extra matches, but for simplicity, I don't think it is so bad to live with.

**Comment by victor0d** [comment]
I think the current pre-release is very very good.
Entering the same keyword several times will still generate a match against the same tag/name, but this is a side effect that I think is very acceptable.
I believe this issue could be close with the current implementation.
