### ISSUE TITLE
Add Backup for Shortcuts

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#241]
If I have not missed anything out, I believe that shortcuts are not included in any of the backup options.

Sometimes apps creates automatic shortcuts, but  other ones that are manually added. It is nice to backup all of them to save time recreating them. Obviously, from the backup point of view, dumping all of them, is the only feasible way. The user could manually edit the xml file if he/she wants to filter anything there.

Is this easily doable ?

**Comment by TBog** [comment]
Shortcuts can not be restored in the latest versions of Android SDK. The launcher only gets an ID for the shortcut and requests more info from the system. When you change the default launcher all shortcuts get reset, at least in my tests.

What I wanted to add to the launcher is a way to make intents. These can be saved but are not easily understood by the average user.

**Comment by victor0d** [comment]
Argg !!! Sorry for the request. I should have known/checked that.

In my tests (but this is on Android10), when changing the launcher, the shortcuts don't get reset, but they can't be used anymore (until the launcher is reverted). Once the launcher is re-selected as default, all the old shortcuts are there and usable again.
In other words, the shortcuts are kept associated to each of the launchers in my tests (Android10).

I use Shortcut Maker too. It is an amazing app, especially in combination with your launcher. Your suggestion to have a method to create intents and possibly backup the history (similar to the history that Shortcut Maker keeps) but that could be run as a batch (this is missing in Shortcut Maker) would be very good. Obviously for the time being Shortcut Maker exists as an option.

Do you think I should I close this request? Or do you want it open for reference ?

**Comment by TBog** [comment]
Can't backup shortcuts on the latest version of Android and I'm not willing to add this feature only for the versions that this is possible.

**Comment by victor0d** [comment]
Completely agree with you.
