### ISSUE TITLE
Keyboard stays active when leaving Search-Desktop

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#242]
Having the setting \<Link keyboard to search bar visibility\> = 0 (OFF)
- When executing a search in Search-Desktop,
- and jumping to Empty-Desktop or Widgets-Desktop though a button or gesture,
- the keyboard doesn't get dismissed.
- At this point, it is still possible to exec a search. The typed text is invisible, but the search results appear on the screen. 

The expected result would be to dismiss the keyboard when leaving the Search-Desktop (or enable the Search-Bar - but I believe this one goes against the intended architecture of the app).

The screenshots show:
1- Search-Desktop with the keyboard active.
2- Widgets-Desktop after jumping from Search-Desktop by pressing Home-Button (the keyboard stays active)
3- Widgets-Desktop while typing and search brings results (without Search-Bar) 

![Screenshot1](https://user-images.githubusercontent.com/90806717/151664847-e8fa853b-b0bb-4bf1-bb12-77d0c10dcc36.png)

![Screenshot2](https://user-images.githubusercontent.com/90806717/151664856-6485842c-7d3c-4833-938a-f2c7445ce442.png)

![Screenshot3](https://user-images.githubusercontent.com/90806717/151664863-845a3db9-79a7-47f9-b6a5-1d7295305176.png)

[backup.xml.zip](https://github.com/TBog/TBLauncher/files/7963900/backup.xml.zip)

Device: Oneplus6
OS: CRDroid6.23(Android10) GApps-less
TBLauncher: 6.8

**Comment by TBog** [comment]
can you please test my fix in [v6.9-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.9-dev.1)

**Comment by victor0d** [comment]
Hi TBog,
I have tested/tried a few combinations of related settings and I had not managed to break it.
You are amazing.
Both issues ( https://github.com/TBog/TBLauncher/issues/242# and https://github.com/TBog/TBLauncher/issues/242 ) are fixed.
Thanks.

**Comment by victor0d** [comment]
Sorry I miscopied the same link twice, in the previous comment:
Both issues ( https://github.com/TBog/TBLauncher/issues/238 and #242 ) are fixed.
