### ISSUE TITLE
Tag Manager fails to edit Tag Icons in v6.9

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#244]
It was working in version 6.8 but it fails in version 6.9:
- Trying to edit any new tag's icon will fail with a toast:
   **Could not find "tag://\<tag-name\>"**
- Any tag that had an icon previously (for example loaded from a backup) will work as expected.
- It also can be reproduced in a fresh installation of the app trying to edit any tag's icon.

![Screenshot_20220202](https://user-images.githubusercontent.com/90806717/152049311-7e3e84b5-3b81-4b9a-ade5-23598bcf785f.png)

**Comment by TBog** [comment]
Do you find it inconsistent that when you change a tag icon from this menu then press cancel on the menu the change remains?

**Comment by victor0d** [comment]
Yes, a little bit :o)
Being strict with consistency, the icons should be reversed back, when cancelling.
But considering that this menu is used, compared to the main desktop screens, quite little, I think most users could accept it easily.

**Comment by TBog** [comment]
1. Maybe I should remove the "change icon" button from this menu. 
Right now it's kind of useless to store custom icons for any tag.
2. Or maybe I should add an option to replace text tag labels of results with the icon of the tag.
This way tags with long text will take up a small space and results could display a lot more tags

**Comment by victor0d** [comment]
My thoughts TBog,
- Currently the usage is limited to assign icons for the Favorites_Bar or Tags_Menu displayed as Search_Result or displayed as Pop-Up.
- Removing the Change_Icon, will make harder to assign icons for anyone using the Tags_Menu displayed as Pop-Up (displayed as Search_Result or in the the Favorites_Bar will still be easy to add/modify icons through the context menu).
- The option to change tags with icons in the Result_Panel sounds like a fun feature. But personally I would prefer the text version of the tags:
-- to understand what is matching.
-- and cuz having a long line of icons will make me dizzy :o)
-- I would prefer two lines of tags if many tags need to be displayed.
- I completely agree with you that the cancel is useful to undo delete and rename, and can become a bit dangerous is removing it completely.
- Having a separated menu for the icons seems redundant, and actually it feels quite natural to select the icons where it is right now.
- Unrelated to the icons, it would also feel natural within the tags menu to click under the number of matches and see the actual list of apps/shortcuts with that tag (this is just a side note).

1) I think the simplest option is renaming "Cancel" -> "Cancel Del/Rename" (Or notify that the icon changes will not be reverted), but I may agree that it is not very elegant.
2) Removing the icon_change from the tags_menu and moving it somewhere else is a possible option, but it will also remove some value from the tag_manager.

**Comment by TBog** [comment]
> Removing the Change_Icon, will make harder to assign icons for anyone using the Tags_Menu displayed as Pop-Up (displayed as Search_Result or in the the Favorites_Bar will still be easy to add/modify icons through the context menu).

This can be addressed by assigning long touch to the popup as change icon

**Comment by victor0d** [comment]
Yes, I agree. A pop-up within a pop-up is normally not right.

**Comment by TBog** [comment]
Made cancel "revert" icon changes from tag manager. 4e1835273321e896d59fa4047025e651309b6987
What the code actually does is to change the icon from the tag manager list then when OK is pressed apply the changes to the database and loaded tag entries.

**Comment by TBog** [comment]
> Unrelated to the icons, it would also feel natural within the tags menu to click under the number of matches and see the actual list of apps/shortcuts with that tag (this is just a side note).

But doing this would close the menu, right?

**Comment by victor0d** [comment]
> What the code actually does is to change the icon from the tag manager list (instead of the tag entry) then when OK is pressed apply the changes to the database and loaded tag entries.

This is indeed the best solution in my opinion. And how the user will expect the behavior. Looking forward to test it.

 

> But doing this would close the menu, right? [11ff0e7](https://github.com/TBog/TBLauncher/commit/11ff0e7fe5a6d24a31c9f457b3dd812444227f64)

This is a very good question. Yes, it has to close the menu to show the tags. Now, would the user expect to go back to the tag manager menu?. I think, from the code point of view, it will be much simpler not to have a way back. And I would think it would be ok just showing the tags and exiting the tag manager.

**Comment by TBog** [comment]
> And I would think it would be ok just showing the tags and exiting the tag manager.

But you are going to lose all changes, just like pressing cancel. I think I'll need to add a confirm dialog when changes are pending.

**Comment by victor0d** [comment]
It is a very good point. I can think on two options:
- Either a confirmation dialog (as you suggest)
- Or showing the apps in a non-clickable menu (not leaving the tag manager), just to show what apps have assigned the tag. This way the apps are shown in a menu (or list) within the tag manager.

**Comment by TBog** [comment]
>Or showing the apps in a non-clickable menu (not leaving the tag manager), just to show what apps have assigned the tag. This way the apps are shown in a menu (or list) within the tag manager.

I can change the tags manager `ListView` to an `ExpandableListView` (see [examples](https://www.google.com/search?q=android+expandablelistview+example&tbm=isch)) but I really don't see why.

I don't understand the way you are using the tags manager that requires you to know what list of apps a tag has.

The **tags manager** started as a debug menu that I started to use when I wanted to show people that tags are useful and easy to use (**tags manager** was only used for renaming tags).
Then I added the icon customization because it was easy to do.
When the **tags menu** was requested the icon changing in the **tags manager** became useful. The only other way to change the icon of a tag is by first adding it to the **Dock**.

**Comment by victor0d** [comment]
Hi TBog,

To be honest, I am happy enough with the current functionality of the Tag Manager. 
Actually I gave you my feedback in reply to your question and how (for my point of view only) could be improved.

So, I think that dropping that functionality (for simplicity) will be more than acceptable.

In any case, and to answer your question; in some cases, I may have some apps, shortcuts, contacts, that have a common tag assigned. But suddenly, one day, I realize one day that I have some missing. Then I review what apps may have the tag missing and I could use this functionality.

Nevertheless, and again, it is not a very important feature. It just feel natural and sometimes useful. But not extremely important.

**Comment by victor0d** [comment]
Indeed working as intended !!!
Excellent TBog
