### ISSUE TITLE
Accessibility Screen Off action

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#245]
Following the feature "double tap to sleep" https://github.com/TBog/TBLauncher/issues/138 closed now.
I would like to request a new action that could be assigned to gestures to have Screen-Off, asides of Lock-Down (currently implemented), and that allows to re-open the phone using the finger-print or face-recognition.
1) **Lock down** (requires Device Admin permissions) and it's implemented already
2) **Screen off** (requires Accessibility permissions) and it is implemented in KISS.

In the case of KISS, only the (2) is available.
In the case of other launchers like Nova, both options (1) and (2) are available.

I guess the code from KISS could be integrated directly.
Thanks TBog.

**Comment by TBog** [comment]
AFAIK using Accessibility will degrade battery performance.

**Comment by victor0d** [comment]
Thanks for the feedback TBog. I was not aware of this.
In this case, I guess we could drop the feature.
Shall I close it (as dropped)?

**Comment by TBog** [comment]
It's not dropped, just not a priority for me right now.
If anyone is interested in contributing I can merge the PR.

**Comment by victor0d** [comment]
Understood. I will take a look, see if I can pull the code in.

**Comment by victor0d** [comment]
Hi TBog,
A comment on this.
With the new feature  Run/launch shortcut with gestures #257 (it is a really cool feature. Thanks TBog) this could be easily implemented creating a shortcut of another app that implements the screen off through Accessibility.
Using shortcuts maybe cumbersome for users with basic capabilities, but the rest could easily implement it.
I still have to bring the functionality in, with KISS code though. I am not dropping this task for now.

**Comment by Wendigogo** [comment]
Hello,
@victor0d : could you please share some apps implementing that kind of shortcut please ?
I didn't know that accessibility services will drain battery, that's good to know. Anyway, using double-tap to lockdown doesn't allow me to use fingerprint sensor when I want to unlock my device : it asks me to use pincode everytime and that is a pain Imo.
Maybe it's a bad setting on my own but on KISS I don't have this "issue" (or feature ^_^). So I guess it's due to this difference between lockdown vs Screen off.

Enjoy!

**Comment by victor0d** [comment]
Many of the launchers have that intent that could be converted into a shortcut with apps like "Shortcut Maker".
You could install a basic launcher only for the intent if your ROM's one doesn't have it.
Otherwise, there are other apps related to power that also have it, like "Power App".

**Comment by Wendigogo** [comment]
> Many of the launchers have that intent that could be converted into a shortcut with apps like "Shortcut Maker". You could install a basic launcher only for the intent if your ROM's one doesn't have it. If you have read the whole trail, you could guess easily that KISS could be one of them. Otherwise, there are other apps related to power that also have it, like "Power App".

I should be a dumbass but I didn't find how to do that. 
I tried many "shortcuts makers" but only intents I found on KISS Launcher are related to launch it or its settings.
Nothing obvious about "screen" or "lock" keywords too.
My device is not rooted by the way.

Thanks for your help.

**Comment by victor0d** [comment]
@[Wendigogo](https://github.com/Wendigogo) you can use the app "Lock". It is available in F-droid or github (https://github.com/seguri/lock). It doesn't require root and actually you don't need any shortcut. Just invoke the app after giving the accessibility permissions. It doesn't require anything else. I am not using it because with root I have many other options, but I have just tested and works flawlessly.

@TBog , just as a thought, maybe this code could be used (rather than KISS's). It is extremely simple. Nevertheless, if you think that accessibility permissions draws extra power, maybe it is a good idea having the functionality in a separated app like this one. This way, it will only be invoked when required, and it will be put down to sleep by the OS otherwise (saving power this way).

**Comment by TBog** [comment]
Using that app is a great idea. No need to integrate it into the Launcher

**Comment by victor0d** [comment]
Sounds good.
Should we document it somewhere and close after this entry?

**Comment by TBog** [comment]
In the documentation or the FAQ
unfortunately we currently don't have either one. 

We could start a discussion and post there some tricks you are using and then we'll make a PR with them to the main page

**Comment by victor0d** [comment]
Yes, I think maybe FAQ is better at this point. Easier to maintain.
I will close this one, and start a discussion as you suggest.
