### ISSUE TITLE
Dock shows on Search when turned off 

### ISSUE THREAD

**Issue by Velcorn** [TBog/TBLauncher#247]
I have turned off the dock for the search screen and further turned off the option to show it with a result list. However, the dock appears when typing. I would expect the dock to not show up in search mode at all when turned off.

I'm on a Pixel 6 running A12 and the latest app version.

**Comment by TBog** [comment]
> I'm on a Pixel 6 running A12 and the latest app version. 

Latest stable or dev version?

**Comment by TBog** [comment]
At first I did not understand what you wanted. It should be fixed in the next release.

**Comment by TBog** [comment]
You can test the fix in release [v6.9-dev.3](https://github.com/TBog/TBLauncher/releases/tag/v6.9-dev.3)

**Comment by Velcorn** [comment]
Thanks a lot for the very quick fix. Keep up the great work!
