### ISSUE TITLE
Submit to F-Droid? 

### ISSUE THREAD

**Issue by esmoak** [TBog/TBLauncher#25]
Does this meet F-Droid requirements, or possibly IzzyOnDroid criteria?

It would be great to get this launcher via those repos.

**Comment by HunterArmstrong** [comment]
As of right now, I don't really know if @TBog put TB Launcher on those sites. Could you not install the app from Google Play?

**Comment by esmoak** [comment]
@HunterArmstrong yes, I got it from play store, but I like to get from F-Droid, plus it will get more users and contributions from F-Droid instead of the sea of launchers in Play store.

**Comment by HunterArmstrong** [comment]
Okay. Understood. But, i didn't make TB Launcher. So, i cant really make that type of choice.

**Comment by TBog** [comment]
I made a request here: https://gitlab.com/fdroid/rfp/-/issues/1424

**Comment by esmoak** [comment]
It finally made it there:

https://f-droid.org/en/packages/rocks.tbog.tblauncher/
