### ISSUE TITLE
Open_Keyboard Action (and go to "Search_Desktop")

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#250]
Following the discussion in https://github.com/TBog/TBLauncher/issues/231 I would like to write a formal feature request to have an action (linked to gestures) to "**Open_Keyboard**", and go to "**Search_Desktop**" in case it is executed from a different Desktop.

This way, having **\<Link keyboard to search bar visibility\> = 0** (OFF) can allow different actions with a single gesture/touch:
- Search directly (using Open_Keyboard action) with the keyboard
- Open history/tag/apps/... with the keyboard dismissed

Maybe this should be linked to https://github.com/TBog/TBLauncher/issues/231

**Comment by TBog** [comment]
**Show <Search> desktop** already exists. Is it not working as expected?

**Comment by victor0d** [comment]
Sorry for not being clear TBog.

Yes, "Show_Search_Desktop" works as expected.

Nevertheless, the request is about **Show_Keyboard** (and moving to the **Search_Desktop** at the same time).

This currently can be done with \<Link keyboard to search bar visibility\> = 1 (ON). But in this case, when showing only tags (no searching) or the history or the recents, ... it will also show the keyboard (and actually may not be required)

In this way, I could:
- "Go_To_Search_Desktop" with keyboard visible when I intend to search.
- and "Go_To_Search_Desktop" without keyboard when I intend to open an app or contact or shortcut from the history or the favorites.
