### ISSUE TITLE
Normalize Shortcut and App Icons in Dock

### ISSUE THREAD

**Issue by cottagepainter** [TBog/TBLauncher#263]
**Description**

This is purely an aesthetic issue. Currently in the dock, app icons and
shortcut icons scale differently. It looks bad when you have icons of
both type in the dock.

**Solution**

Have the option to make them look the same.

**Comment by TBog** [comment]
Can you please post an image with the issue and the settings (values in the preferences) you used?

**Comment by cottagepainter** [comment]
Yes sir

Here is the screenshot,
![Screenshot_20220315-080757_TinyBit_launcher](https://user-images.githubusercontent.com/48231298/158326949-1e91b879-efe5-4c06-9c72-108f80b81022.png)

The app is on the left, and a shortcut with the same icon is to its right. As you can see they are scaled and positioned
differently within their 'divs'. 

I've tried every setting there is (i think) to try and change this but nothing works. I work around this by just using icons
of one type (in my case shortcut icons). This in itself leads to another aesthetic issue which i will open another issue for.

Here are the all the relevent screenshots of my settings (i assume). Let me know if i missed anything


![Screenshot_20220315-082817_TinyBit_launcher](https://user-images.githubusercontent.com/48231298/158328522-2b6e7f86-a737-4399-a4ea-b90892146858.png)
![Screenshot_20220315-082840_TinyBit_launcher](https://user-images.githubusercontent.com/48231298/158328527-30c086a0-5800-41d9-a94a-e591c3dc0262.png)
![Screenshot_20220315-082916_TinyBit_launcher](https://user-images.githubusercontent.com/48231298/158328541-f1c31768-1ecd-4982-b941-0835357fb9a8.png)
![Screenshot_20220315-082937_TinyBit_launcher](https://user-images.githubusercontent.com/48231298/158328545-5263687c-aeb7-48b5-8f44-4db5bda5e08c.png)
