### ISSUE TITLE
New icon suggestion

### ISSUE THREAD

**Issue by Donnnno** [TBog/TBLauncher#266]
Hi!
I was in the mood to design/ redesign some icons, and I came up with this for TinyBit, let me know what you think of it.

![image](https://user-images.githubusercontent.com/31142286/159127810-3bc369e7-3750-4b75-a82a-91843cf28ea5.png)

**Comment by ltGuillaume** [comment]
Looks pretty cool

**Comment by TBog** [comment]
It looks great.
Can you make a SVG out of it?

**Comment by Donnnno** [comment]
Thanks!! 

I'll make a svg out of it, and make a PR with the app icons in place :)

**Comment by Donnnno** [comment]
Also, which one do you like the most?

**Comment by TBog** [comment]
I'd love to change the 9 square icon next to the search bar with this, but I'll see how the svg looks before promising anything.

I'd have to be able to
1. easily rotate it (I can't see why it would be hard)
2. change the color based on user preferences. Looking at the current design I'd probably need 2 colors which is not a problem.
3. make it look good in a small resolution

**Comment by Donnnno** [comment]
Both SVG's:

![tinybit_v1](https://user-images.githubusercontent.com/31142286/159133296-6dca2364-e2ea-498f-b955-7d5436b0541e.svg)
![tinybit_v2](https://user-images.githubusercontent.com/31142286/159133297-ec9f791d-cdea-4e18-aa75-1e0071be7317.svg)

Let me know if it works!

**Comment by Donnnno** [comment]
You can also delete the background, I think it fit's better in the launcher that way.

**Comment by TBog** [comment]
![cube-small](https://user-images.githubusercontent.com/6465804/159138006-736bc482-261c-480f-8e43-17d1c15bdfef.svg)

I made it smaller, is it still looking ok on your devices?
As soon as I get to my PC I'll test if I can import it into Android Studio

**Comment by Donnnno** [comment]
Smaller in what way?

Still looks almost the same, I noticed some subtle shadows are gone now. Would make sense in app, but my suggestion would be to leave those effects in there in the app icon :)

**Comment by TBog** [comment]
> Smaller in what way?
> 
> Still looks almost the same, I noticed some subtle shadows are gone now. Would make sense in app, but my suggestion would be to leave those effects in there in the app icon :) 

The file size. Look at the SVG code.
There were some embedded PNG in the SVG that I removed. I didn't notice the difference on my phone.

**Comment by Donnnno** [comment]
Yeah, it's way smaller, that's good for the app :) 

the PNG embeds were some raster effects like subtle shadows that gave the icon more depth

**Comment by TBog** [comment]
> the PNG embeds were some raster effects like subtle shadows that gave the icon more depth

Yes, I'll keep them for the launcher app icon.
I'll have to see how to change https://github.com/TBog/TBLauncher/blob/master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

**Comment by Donnnno** [comment]
No worries about that, I can do it for you.
It only takes a couple of secs for me. 

Kinda an expert on android icon stuff haha 😄

**Comment by Donnnno** [comment]
I created a pull request, it's still a draft, but contains everything that you need for the app icons :)

**Comment by Donnnno** [comment]
I do have to say that the greenish tint that I choose, doesn't fit the launcher's theme tho. 

I tried it with the super saturated tint from the launcher, but that doesn't look as sleek as this one, unfortunately..

**Comment by ltGuillaume** [comment]
Well, perhaps you could turn it around and make the green theme match the icon. That would make much more sense imho, because the current green theme is quite ugly 😋

**Comment by Donnnno** [comment]
I think it could work out pretty nicely with these colors.

![image](https://user-images.githubusercontent.com/31142286/159168983-90725880-e3e7-4d70-942a-337b152b3591.png)

Also, a featuregraphic like this would look very refreshing:

![image](https://user-images.githubusercontent.com/31142286/159169006-89181263-a5be-41ae-a88f-4dab6e801ed9.png)


But.. I'm kinda going to fast already with these designs... :) 

Let me know what you think of it @TBog and say if it goes against the concept of your app!

**Comment by TBog** [comment]
Ill make the default theme with the colors you provided; hope it'll look good.

**Comment by TBog** [comment]
Default theme added here: 63be5db0470865a1f6f50102759a3b465cb852ae
This should be a good example of how to add a theme

**Comment by Donnnno** [comment]
Cool! Do you have a screenshot or something? dunno how to view specific commits in android studio :')

**Comment by TBog** [comment]
> Cool! Do you have a screenshot or something? dunno how to view specific commits in android studio :')

It's on the [develop](https://github.com/TBog/TBLauncher/commit/63be5db0470865a1f6f50102759a3b465cb852ae) branch.

**Comment by Donnnno** [comment]
This looks really clean!

![image](https://user-images.githubusercontent.com/31142286/160259990-2b1592fe-c36c-490e-af8a-5a2421be83ca.png)

**Comment by Donnnno** [comment]
Closing this, if you need help with further design stuff, just let me know!
