### ISSUE TITLE
Multiple rows in dock

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#270]
**Description**
I've seen some people say that other launchers have the possibility to add multiple rows to the dock.

**Solution**
Allow the user to choose the row count for the dock. 

**Alternative solutions**
When there are too many icons in the dock, instead of making the icons smaller, move them to a new row. 

**Additional context**
Do dock rows have individual icon count?
If not then how does the user choose the row item count?
Should each dock row have it's own background?

**Comment by TBog** [comment]
Multiple rows added with commit https://github.com/TBog/TBLauncher/commit/4253baf56d0a2859fa9a40651718058b69c87b32

**Comment by lgwapnitsky** [comment]
Great. When will this be up on fdroid?
