### ISSUE TITLE
"Go to Search_Desktop with Keyboard" doesn't work from "Widgets_Desktop"

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#272]
Hi TBog,
Thanks for adding the feature Open_Keyboard Action (and go to "Search_Desktop") #250.
It is good.
Nevertheless, it only works from the Search Desktop.
Would it be possible to make it work from Widgets Desktop (and possibly Empty Desktop)?
Thanks,

**Comment by TBog** [comment]
You want an option called "Go to Widgets_Desktop with Keyboard"?
Can you please give a concrete example of what you want?

**Comment by victor0d** [comment]
Sorry I wasn't clear TBog.
The feature should take me in one step to Search_Desktop and open the keyboard.
For example: From Widgets_Desktop
* I could have a gesture assigned to `Go Search Desktop with keyboard` and when using it, I shall go from Widgets_Desktop to Search_Desktop and open the keyboard all in one step.
* At the same time (only for the sake of the real case example) I can have a different gesture assigned to  `Show Recent History` and when using it, I will go from Widgets_Desktop to Search_Desktop and shows the history (without the keyboard) in one step. THIS CURRENTLY WORKS AS EXPECTED !!

Nevertheless, the current implementation of `Go Search Desktop with keyboard` do it in two steps if I am in Widgets_Desktop: 
- From Widgets_Desktop it takes me to Search_Desktop without keyboard
- From Search_Desktop it opens the keyboard (this is as expected)

**Comment by TBog** [comment]
Is this fixed in release [v6.12](https://github.com/TBog/TBLauncher/releases/tag/v6.12) ?
If not then please update the steps needed to reproduce.

**Comment by victor0d** [comment]
Hi TBog,
Working perfectly. THANKS.
It can be closed now.
