### ISSUE TITLE
`Hide when no results` text not clear

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#273]
I was reading the text toggle in the settings and I think we should make it cleared because it doesn't include the word DOCK:
`Hide when no results` (Visible when the result list has entries)
I think it maybe better adding the word DOCK, otherwise it seems unclear:
`Hide dock when no results` (Visible when the result list has entries)

_Originally posted by @victor0d in https://github.com/TBog/TBLauncher/issues/256#issuecomment-1086231523_

**Comment by ltGuillaume** [comment]
Absolutely. I was also confused about the setting's effect.
