### ISSUE TITLE
"Back" action when closing keyboard not working 

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#276]
I don't think this is fixed properly:

- Enable `"Back" action when closing keyboard"` on a Samsung S5, Android 10: the keyboard is closes with the Back button, but it does NOT trigger the "Back" action.
- Disable `"Back" action when closing keyboard"` on a Nokia 3, Android 9: the keyboard doesn't even close, i.e. the Back button is blocked completely. (Enabling the option _does_ trigger the "Back" action on this device.)

_Originally posted by @ltGuillaume in https://github.com/TBog/TBLauncher/issues/238#issuecomment-1086938116_

**Comment by TBog** [comment]
I hope this will be fixed by PR #275

**Comment by TBog** [comment]
@ltGuillaume can you check if it's fixed on [v6.12](https://github.com/TBog/TBLauncher/releases/tag/v6.12)

**Comment by ltGuillaume** [comment]
Just checked the first point on S5: still the same issue with 6.12... Will check the second point ASAP.

**Comment by TBog** [comment]
Then maybe commit 345f2fa6b70c55bb41808fcfe8aa6cb65a0efe1a will fix it.

**Comment by TBog** [comment]
please try [v6.12-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v6.12-dev.1)

**Comment by ltGuillaume** [comment]
Yes, this fixed it!

**Comment by ltGuillaume** [comment]
Oops! This introduces a new problem! When scrolling down through the list, the keyboard is hidden, but then the Back action is immediately called as well (which in my case triggers the widget mode). So, I can't scroll through the result list anymore...

**Comment by TBog** [comment]
> When scrolling down through the list, the keyboard is hidden, but then the Back action is immediately called as well

fixed with commit 489924afdcb0ac1f1b5375a62af3b6f24b9eab60
I just hope I didn't introduce any other unintended features (_bugs_) with this commit :grin:

**Comment by ltGuillaume** [comment]
I'm not sure if that commit will also tackle the following:

1. When trying to change the icon via the context menu, the dialog immediately closes after opening, because the keyboard is closed first, which triggers the Back action.
1. When trying to pick an icon from an icon pack and pressing Enter after I typed the search term, the keyboard closes, but this also closes the entire icon picker dialog (i.e. the Back action is triggered).

**Comment by TBog** [comment]
Thanks for reporting, I'll check it and see if I can make a new dev release

**Comment by ltGuillaume** [comment]
> I'm not sure if that commit will also tackle the following:
> 
>     1. When trying to change the icon via the context menu, the dialog immediately closes after opening, because the keyboard is closed first, which triggers the Back action.
> 
>     2. When trying to pick an icon from an icon pack and pressing Enter after I typed the search term, the keyboard closes, but this also closes the entire icon picker dialog (i.e. the Back action is triggered).

FYI, both (1) and (2) are still present in 6.14.

**Comment by TBog** [comment]
Thank for pointing it out, I'll try to reproduce the issue on the emulator.
I understand why it would happen, just need to find a good way to fix it.

**Comment by ltGuillaume** [comment]
These two issues have been resolved in the 6.14dev1 release, thanks!
