### ISSUE TITLE
`Show dynamic in results` toggle not working

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#278]
Disabling `Show dynamic in results` does not seem to work:
1. the dynamic shortcuts still show up as results while typing
2. they show up among the `Untagged` items.

_Originally posted by @ltGuillaume in https://github.com/TBog/TBLauncher/discussions/269#discussioncomment-2497245_

**Comment by TBog** [comment]
1. Only the manifest shortcuts and pinned shortcuts (not the dynamic ones) show as results while typing
2. because they are `Untagged`

It looks like previously the manifest shortcuts did not appear as results. I'll fix this.

**Comment by ltGuillaume** [comment]
Ah yes, I knew it was a subset, but didn't realize what it was. Thanks for fixing it!
