### ISSUE TITLE
[BUG] Text too dark in settings

### ISSUE THREAD

**Issue by esmoak** [TBog/TBLauncher#28]
**Describe the bug**
After I upgraded to version 4.5, when I click on the Launcher settings the settings text is too dark. Also applies to the WIP version

**To Reproduce**
1. Go to TB launcher settings
2. The launcher appears to go to a dark mode and I can't read the text.

**Expected behavior**
Readable text

**Smartphone (please complete the following information):**
 - Huawei mate
 - Android 8.0
 

**Additional context**
I attempted to change my wallpaper from light to dark backgrounds and vice versa in the text still is unreadable.

I also cleared app data and reinstalled and it was the same. Did not happen with previous version

**Comment by TBog** [comment]
should be fixed in c45d7819dfc36eba3138a60c04d59e6749013cd1
I'll try to make a new GitHub release today so you can still use the app

**Comment by esmoak** [comment]
Confirmed fixed in v4.6-testing.2
