### ISSUE TITLE
[FEATURE] Reset text input when tapping on another icon

### ISSUE THREAD

**Issue by esmoak** [TBog/TBLauncher#29]
Current behavior: 
- place heart icon for favorites in the quick list
- start typing something like "br"
- list of apps gets searched with some results such as Bromite showing in the search.
- decide I want to click on my heart icon for favorites instead
- no apps appear because "br" stays in the search box (it appears that favorites aren't searchable so I'm not sure why this affects it)
- have to delete the "br" for apps to appear in the heart icon for favorites

Suggested change:
- tapping on any icon clears the text field
- possibly offer a toggle switch to adjust this behavior so users have a choice

Perhaps the current behavior is intended, but to me it seems like a smoother workflow to reset the text input.

Edit: ironically, if I search for nonsense that doesn't match any of my apps, like "64386" then when I click on my heart icon for favorites then all the favorites appear as if the search had no affect.

**Comment by TBog** [comment]
There seems to be a bug with the favorites filter, I'll look into it, but it is supposed to be a filter.

The filters in the Quick List are just that, filters. Say you want to find a contact, you type part of the name and lots of apps also show in the results, you then press the contact filter and see only the contacts matching. The same should also be true for apps and favorites. I don't have the skills to make a better icon for the filters.

What I did is that when the result list is empty (the search bar is empty or no results found from the search) then the filter would display all possible values.

**Comment by esmoak** [comment]
Thanks! I was trying to update my original comment for clarity when you typed this.

I have no problem with the icons themselves.

Thanks

**Comment by TBog** [comment]
> I have no problem with the icons themselves.

What I meant was that maybe there should be a clue in the icon of the filter that it's a filter, like ⧩ or a [funnel](https://feathericons.com/?query=filter)

Also I should include buttons for what you wanted, strait up clear or ignore the search bar and show the apps or contacts or favorites. These should also sort the list, right now we don't have any order to the list (except for when searching).

We also lack a way to show all apps and multiple buttons with different order could be a solution.

**Comment by TBog** [comment]
I added buttons for showing the app list, sorted and clear the search bar, please check latest GitHub release.
