### ISSUE TITLE
When adding search engines, use the site's favicon as an icon

### ISSUE THREAD

**Issue by magnus-ISU** [TBog/TBLauncher#298]
**Description**

Currently, added search engines get a default magnifying glass icon. It would be pretty cool if they instead showed the favicon for the site, to distinguish for example github from duckduckgo from brave search from whatever other random sites I might want to add.

**Solution**

When adding a custom search engine, download the favicon and set it as an icon.

**Alternative solutions**

Allow users to set custom icons for search engines manually.

**Additional context**

**Comment by magnus-ISU** [comment]
i'm stupid and didn't search through closed issues.

I still think automatically getting favicon would be cool, but the alternative solution is already here.

**Comment by TBog** [comment]
This app doesn't have internet access on purpose.

There should probably be an option to set the icon when you add the search engine

**Comment by TBog** [comment]
I was thinking of adding the option to change the icon in the preference dialog that one uses to add the search engine.
Now that I double checked it would complicate the UI too much.
