### ISSUE TITLE
Blurry text on search bar when background is light

### ISSUE THREAD

**Issue by Llamach** [TBog/TBLauncher#299]
**Description**
- When the background of search bar is light colored, the text shadow makes the search hint look blurry.

**Solution**
- An option to toggle text shadow on/off would make it better.

Edit
This can be done to search results as well

**Comment by Llamach** [comment]
![Screenshot_20220606-170120_TinyBit launcher.png](https://user-images.githubusercontent.com/106749236/172153121-49e02c2a-d224-4173-ae15-ba9e27dc1a8f.png)
This is what it looks like

**Comment by TBog** [comment]
It looks horrible.
I'll have to add options for color and size.

**Comment by TBog** [comment]
@Llamach is the shadow preference from <a href='https://github.com/TBog/TBLauncher/releases/tag/v6.15-dev.3'>Update 6.15 - dev.3</a> looking OK?
