### ISSUE TITLE
Edit/Remove shortcut list from app menu

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#30]
**Is your feature request related to a problem? Please describe.**
There is often a huge list of the shortcuts I added from an app when I tap and hold the app icon.

**Describe the solution you'd like**
I think there should be an option to either remove that shortcut list from the app menu or remove certain shortcuts from the menu

**Comment by TBog** [comment]
My mistake, the context menu should hold only dynamic shortcuts, not all of them.

**Comment by HunterArmstrong** [comment]
Okay. No problem! 👍🏻

**Comment by TBog** [comment]
removed pinned shortcuts here: bfee35bab7590d029fc8b96f25a5dbf3455d1ae6
WhatsApp still has lots of dynamic shortcuts tho'
