### ISSUE TITLE
Shortcut in app Context Menu

### ISSUE THREAD

**Issue by Llamach** [TBog/TBLauncher#300]
**Description**
App shortcuts in app context menu for applications

**Solution**
1. App shortcuts appears on result list when searching.
2. Long pressing apps on app list or search list opens shortcuts along with context menu

**Comment by TBog** [comment]
There are a couple of types of shortcuts.

The dynamic shortcuts already appear in the long-press menu (option to toggle this in preferences)

The other shortcut types appear in the results list because there could potentially be thousands. You can create one for each website you visit.

**Comment by Llamach** [comment]
This is offtopic question...
Is this option present in `KISS Launcher`?

**Comment by TBog** [comment]
> Is this option present in `KISS Launcher`?

I don't think it is.
I rewrote much of the code that was dealing with shortcuts.

**Comment by Llamach** [comment]
Thanks for the info, have a great day.
