### ISSUE TITLE
[FEATURE] List sorting

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#31]
**Is your feature request related to a problem? Please describe.**
I get a little confused at how the app list is sorted out.

**Describe the solution you'd like**
I feel that a list sorting option should be added to the settings for a little bit of structure.

**Comment by TBog** [comment]
Like I said before, https://github.com/TBog/TBLauncher/issues/29#issuecomment-682479604
there should be buttons for each sort order for the user to choose from, like the filters are now.

**Comment by HunterArmstrong** [comment]
Kay.

**Comment by TBog** [comment]
If you still think we need to work on this, please reopen and add details.

**Comment by HunterArmstrong** [comment]
Adding the actions to the quick list setting made it difficult to scroll down to the favorites list for me. I think the list sorting should be a setting on its own under the user interface instead of a quick list item.

**Comment by TBog** [comment]
This is how it looks on my phone.
![image](https://user-images.githubusercontent.com/6465804/92502296-5781b580-f208-11ea-9de8-6be3c55d3b8b.png)

Both **Possible filters and actions** and **From the favorites** have the same amount of space and can be scrolled independently.

If you find it difficult to navigate I see two options:
1. make it a tabbed view: ![image](https://user-images.githubusercontent.com/6465804/92502874-22299780-f209-11ea-8f4f-bcc0f96af408.png) In this example the **Tab1** would be **Possible filters and actions** and **Possible filters and actions** would be **From the favorites**
2. merge the content of the two grids. This was my first implementation but it just felt weird at the time to have them merged.

**Comment by HunterArmstrong** [comment]
I get that. It works when you pull it up from the homescreen when you hold the apps icon. But it doesn't work well for me in the TB settings under features.

**Comment by TBog** [comment]
> I get that. It works when you pull it up from the homescreen when you hold the apps icon. But it doesn't work well for me in the TB settings under features.

fixed in 1509abc0f04cb4a2be0dae845c8d566d2815c8c4
