### ISSUE TITLE
Set default search engine entry for type-then-Enter

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#312]
**Description**
Personally I keep forgetting that search term+Enter doesn't always use the same search engine.

It would be great to be able to set a default search engine. This way, you can press Enter after typing a longer search term, would have no app/contact search results.

**Solution**
A) Specify a default search engine, or
B) Let the user specify a fixed search engine order, so that the search engines always show up in that order and the first will be used when pressing Enter

**Comment by TBog** [comment]
There is a default search engine

**Comment by ltGuillaume** [comment]
Holy crap, "Make default" is in the context menu! Well, while I feel pretty stupid right now, these _are_ the best kind of issues to open; those to which the answer is "it's already there!". Closing!

**Comment by TBog** [comment]
I'll keep this open so I remember to add the "Make default" option on the result as well.
