### ISSUE TITLE
Horizontal Screen 

### ISSUE THREAD

**Issue by uGeek** [TBog/TBLauncher#336]
**Description**
You have thought about making TB work also with the screen in landscape.
 
This would be ideal for both tablets and mobiles when using it in the car with the navigator in Landscape position

**Comment by TBog** [comment]
Did you try to disable the lock from `Layout` -> `Wallpaper interactions` -> `Lock portrait`

**Comment by magnus-ISU** [comment]
I can use Key Mapper to change to landscape as well. I'm not sure why I'd use it like that though as it is really optimized for having a long list of results. Nevertheless

![image](https://user-images.githubusercontent.com/75949275/184985842-df35d762-9280-4ad0-96b2-682e7c1df223.png)
