### ISSUE TITLE
Screen unlock issues 

### ISSUE THREAD

**Issue by uGeek** [TBog/TBLauncher#337]
**Description**
Every time I lock the screen with TB, when I unlock I need to enter my pin, it does not allow fingerprint unlock

**Solution**
I installed this application which solves the problem and gives the solution. https://play.google.com/store/apps/details?id=com.olalab.lockscreen&hl=en&gl=ES

Only available on Android P and newer: This app uses the new Accessibility Service APIs to lock your phone's screen without disabling the fingerprint on the lock screen. As result of using new APIs; new user permissions have to be included (i.e. WRITE_EXTERNAL_STORAGE ).

**Additional context**
It would be great if it worked perfectly instead of installing an app

**Comment by TBog** [comment]
On my Samsung device I don't have this problem.
I'll try to find a device that exhibits this issue, but right now I can't fix this.

Requiring WRITE_EXTERNAL_STORAGE permissions for locking the screen is suspect imho.

**Comment by TBog** [comment]
> Every time I lock the screen with TB

Are you referring to the Device admin lock screen option from the launcher?

**Comment by TBog** [comment]
See issue #245

> you can use the app "Lock". It is available in F-droid or github (https://github.com/seguri/lock). It doesn't require root and actually you don't need any shortcut. Just invoke the app after giving the accessibility permissions. It doesn't require anything else.
