### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [TBog/TBLauncher#338]
Can the language be changed ?

**Comment by TBog** [comment]
System language is used.
User chosen language should be possible, but not implemented.

**Comment by mondlicht-und-sterne** [comment]
My smartphone is in German (system language) but TBLauncher still only displays English.

![Screenshot_20220814-232441_TinyBit launcher-01](https://user-images.githubusercontent.com/61406324/184555483-93be586e-7f1d-4fcd-b646-d84fc3962bc4.jpeg)

**Comment by TBog** [comment]
### Translation status

[<img src="https://hosted.weblate.org/widgets/tblauncher/-/multi-auto.svg"
      alt="Translation status image" />](https://hosted.weblate.org/engage/tblauncher/)

You can help by translating [here](https://hosted.weblate.org/engage/tblauncher/)

**Comment by mondlicht-und-sterne** [comment]
> ### Translation status
> [![Translation status image](https://camo.githubusercontent.com/8d00c3414c33e6bc8399c3a9e9a3d1967f78fe37e0ff21a0d3175974d1933137/68747470733a2f2f686f737465642e7765626c6174652e6f72672f776964676574732f74626c61756e636865722f2d2f6d756c74692d6175746f2e737667)](https://hosted.weblate.org/engage/tblauncher/)
> 
> You can help by translating [here](https://hosted.weblate.org/engage/tblauncher/)

on strings or on strings-v26 ?

**Comment by TBog** [comment]
strings

**Comment by mondlicht-und-sterne** [comment]
Since it is now clear where it can be translated, I will close here.
