### ISSUE TITLE
[FEATURE] Export settings

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#34]
Multiple export options
* [x] theme (colors and sizes) to make sharing a look easier
* [x] custom icons for apps and tags
* [ ] possibility to make TBL only icon packs
* [x] tags and associated entry IDs
* [x] content of favorites and quick list 
* [ ] feature toggles

- What happens when we export the bar size? it's a linear interpolation that will look different on **mdpi** vs **ldpi**.
- Should we change it to be **dp** or **px**? If we do we'll need to also change the text size.
- Is it ok if we let the user change the bar height and text size independently? We probably need a reset to defaut button to help.

**Comment by TBog** [comment]
Add some color presets (like themes) and allow user to change, rename and restore them.

**Comment by TBog** [comment]
In order to avoid WRITE_EXTERNAL_STORAGE permission use a FileProvider
https://medium.com/androidsrc/share-cache-files-with-other-android-apps-using-fileprovider-897fe5705e45

**Comment by HunterArmstrong** [comment]
Just installed the update. You should also add the setting to export shortcuts.

**Comment by TBog** [comment]
What settings? You mean the other stuff in Features that currently is exported only when selecting backup?
I did not think it would be useful.

If you meant something else please elaborate.

**Comment by HunterArmstrong** [comment]
> would you be able to share your exported interface and backup? 

I'm sorry. I don't know what you mean by this.

- Are you asking if I can share a screenshot of my home screen?
- Are you asking if I know a way around saving the entire widget layout

Or

- Are you asking if I can share the exported backup files that I can supposedly make on TBL?

**Comment by TBog** [comment]
I'm asking if you're ok with sharing the backup.xml file that is exported by TBL

**Comment by TBog** [comment]
There seems to be an issue with some colors, they export with alpha and then fail to import correctly

**Comment by HunterArmstrong** [comment]
Yeah. I'm okay with that. Do you just want me to create a backup file and share it to GitHub?

**Comment by HunterArmstrong** [comment]
[I created a Google Drive file with the export settings](https://drive.google.com/file/d/16WkE-zGde9oll9Z05e-KFqbCRyr3GXHx/view?usp=drivesdk)

**Comment by TBog** [comment]
Now I understand why you want to save the shortcuts :grin: You have a ton of them.

**Comment by HunterArmstrong** [comment]
Frick yeah man. Lol.

**Comment by HunterArmstrong** [comment]
@TBog I'm just wondering, how did you figure out that I had all those shortcuts?

**Comment by TBog** [comment]
> @TBog I'm just wondering, how did you figure out that I had all those shortcuts?

I read the backup file. The exported tags referenced a lot of shortcuts.

The shortcuts are saved by the system and the launcher stores the unique identifier. Once you clear the launcher data the system releases/invalidates the shortcuts/unique identifiers as well.

**Comment by HunterArmstrong** [comment]
Okay. That kinda makes sense

**Comment by HunterArmstrong** [comment]
@TBog I also found another issue with importing the backup settings.

**Comment by TBog** [comment]
> @TBog I also found another issue with importing the backup settings.

Are you going to elaborate?

**Comment by HunterArmstrong** [comment]
Oh yeah. I can't really back up my previous file because it was backed up in a different file format.

**Comment by TBog** [comment]
> Oh yeah. I can't really back up my previous file because it was backed up in a different file format.

I'm not sure what you mean. The backup format never changed. If you have problems please share the files that you have problems with.

**Comment by HunterArmstrong** [comment]
Ok
