### ISSUE TITLE
App list background color and opacity config dialog not opening fully

### ISSUE THREAD

**Issue by cafuneandchill** [TBog/TBLauncher#345]
# Description #
Dialog for App List background color and opacity in TBLauncher settings doesn't fully open.

## Steps to Reproduce ##

To reproduce the behavior:
1. Open TinyBit settings
2. Open Appearance settings
3. Scroll down to App List settings
4. Open *Background color and opacity*
5. See error

## Expected behavior ##
A fully open color chooser dialog which would let me choose opacity for the App List.

### Screenshots ###

![Screenshot_20220918-212016](https://user-images.githubusercontent.com/43551330/190922798-ae47f525-f15f-4f38-a969-48a8653d3c64.jpg)

## Device info ##

  * Device: ASUS Zenfone 2 Laser (ASUS_Z00ED)
  * OS: Android 6.0.1
  * TinyBit Launcher version: v7.1 F-Droid

**Comment by TBog** [comment]
You've been very specific about the color setting you've having problems with. Is it possible that you are having this issue with all color dialogs?

The library I'm using for the color picker is taking a long time to inflate the view so I changed it to inflate asynchronously. I'm thinking this is the issue. 

I'll have to replicate your issue because I'm not sure what can be done about it. Are you willing to test some custom builds so we can find a fix?

**Comment by cafuneandchill** [comment]
No, I believe this only happens with this particular dialog. Some of the other color picker dialogs have a different problem -- they open fully, but *Cancel* and *OK* buttons are partially obscured behind the dialog edge. Mostly, this happens with other *Background color and opacity* dialogs. Other dialogs are fine.

I'm open to any suggestions.

**Comment by TBog** [comment]
The issue in the screenshot you provided is that the title has wrapped and is now on two rows.
Do you have the text size android setting (text magnifier) set to scale up the text?

**Comment by cafuneandchill** [comment]
Yeah, I do. So far, the text size was set on "Regular". If I change it to "Small", the color picker does open up correctly.

The only issue that remains is that "Close" and "Ok" are partially obscured under the lower edge of the color picker dialog. But it's not that big of a deal for me.

**Comment by cafuneandchill** [comment]
Thank you for your help!
