### ISSUE TITLE
Search/Result History

### ISSUE THREAD

**Issue by Jackie7610** [TBog/TBLauncher#347]
How do I turn off the search/result history completely? Is such a feature already implemented? I fail to find the toggle switch to turn it off...

**Comment by TBog** [comment]
I remember seeing this question before but I can't find it anywhere anymore.

You can't turn off the launch history. Why would you want that? It's stored only on your device so nobody else has access to it.

Are you looking to have your search results in the same order?

**Comment by Jackie7610** [comment]
The history covers up the entire homescreen when I bring up the search bar plus I cannot use swipe (fling) gestures when the history is entirely over the screen and to clear out the history one has to remove them one by one which consumes a lot of time. A simple toggle switch to turn off history would be great or maybe limit the history size to 0. There's also something else I'd like to see as a feature. To hide the app entirely from the launcher and not just from the search results.

**Comment by TBog** [comment]
> The history covers up the entire homescreen when I bring up the search bar

There is an option to disable this

**Comment by TBog** [comment]
> There's also something else I'd like to see as a feature. To hide the app entirely from the launcher

How are you supposed to revert this if it's hidden entirely?
I suppose we could have a list of hidden apps in the settings to be able to remove them, but why?

**Comment by Jackie7610** [comment]
> I suppose we could have a list of hidden apps in the settings to be able to remove them, but why?

Because the apps are still visible in the app list and can still be accessed which destroys the point to 'hide' it in the first place. A user who has gained access to the device can still easily find the hidden (not so hidden)  apps.

**Comment by Jackie7610** [comment]
> There is an option to disable this
> 
> Settings -> Behavior -> Desktop mode Search -> Initial result list
> 
> choose Empty

Thanks... this really helped 👍

**Comment by TBog** [comment]
> A user who has gained access to the device can still easily find the hidden (not so hidden) apps.

That's not the intended use case of that feature.

Open a new issue for this if you still think it's necessary.
