### ISSUE TITLE
Color picker/contact-results not adjusting according to screen size

### ISSUE THREAD

**Issue by JayKx** [TBog/TBLauncher#351]
![Screenshot_20221116-194221-01](https://user-images.githubusercontent.com/109192420/202337616-69784a77-a873-4bab-923e-54d0a21de09f.jpeg)
# Look how lower part is not visible in normal display#

## Steps to Reproduce ##

To reproduce the behavior:

## Device info ##

  * Device: 
  * OS: 
  * TinyBit Launcher version:

**Comment by TBog** [comment]
Unfortunately this is in part an issue of the color picker library I'm using.
I changed the layout inflation to be asynchronous because it took a long time for the dialog to open on older devices.
I think I'll have to change the picker. Thank you for posting this issue.

**Comment by TBog** [comment]
duplicate of #345
