### ISSUE TITLE
Search within shortcuts

### ISSUE THREAD

**Issue by abonhote** [TBog/TBLauncher#360]
**Description & Solution**

It's nice to have shortcuts in the long press context menu like other launchers do. However, as TB is all about searching, it would be nice to have them searchable. Like:

Instead of
  Type "pl" (Play store) -> long press -> my apps

You would
  Type "my" -> expand to "Play Store: my apps"

Kiss has this.

Cheers

**Comment by TBog** [comment]
Try to enable `Layout`-> `Shortcut` -> `Show dynamic in results`

**Comment by abonhote** [comment]
Awesome! 😂  I sure came around that spot 20 times today without seeing it. Thanks!
