### ISSUE TITLE
[FR] search filter should also consider the app id string

### ISSUE THREAD

**Issue by ildar** [TBog/TBLauncher#369]
**Description**
Many apps have localized names which aren't always obvious.

**Solution**
searching in English can show the apps because their appid match.

**Alternative solutions**
try&error

**Additional context**
TBL is great. We love it and what it to become better )))

**Comment by ltGuillaume** [comment]
Why don't you just rename the app, so you know what to search for?

**Comment by TBog** [comment]
@ildar could you add tags or rename the app?
The app id is not displayed when searching and the matches will not make sense to the user.

**Comment by ildar** [comment]
> The app id is not displayed when searching and the matches will not make
sense to the user.

That's fair. Should I close this issue?
