### ISSUE TITLE
[BUG] Exclude Button is still a "work in progress".

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#37]
**Describe the bug**
The exclude button on an app menu doesn't actually exclude an app. It either says "Work in progress" for the "Exclude from TB Launcher" button or "not implemented" for the exclude from history button. From what I remember, the original plan was to just remove the button for now and then figure out the rest. The button is just useless right now.

**To Reproduce**
1. Go to 'Apps'
2. Hold on literally any app
3. Scroll down to 'exclude'
4. Tap 'from history' or 'from TB Launcher'
5. See error

**Expected behavior**
I expect there to be no exclude button for right now until there is an exclude button that works

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S10+]
 - OS: [e.g. Android 10]
 - Version [e.g. v4.5]

**Comment by TBog** [comment]
fixed in 300ef7d3ad7312275cd412ac0b7bd85fde80b5ce
