### ISSUE TITLE
Long press home button support

### ISSUE THREAD

**Issue by N1N74** [TBog/TBLauncher#374]
Have been using the app with another launcher using [homebot](https://github.com/s6joui/homebot) to bind long press home key to open TBLauncher. Since latest update (7.3) this isn't working. Would be cool to have this working again. 

Alternatively TBL can improve my use by the following ways:
1. Be able to set as device assistant
2. Searchbar widget that opens to TBL search with keyboard (however [shade launcher](https://github.com/amirzaidi/Shade) identifies a "search widget")

**Comment by N1N74** [comment]
I got it working as long press by running it as shortcut from the same app. Although the suggestions could further improve the app, I think I will mark this issue as closed.

**Comment by TBog** [comment]
I'll research that KISS has done about device assistant and try to bring that functionality
