### ISSUE TITLE
[FEATURE] Exclude Button

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#38]
[From TBLauncher#17]

> This feature is not currently working anymore. I need to hide the excluded apps from the filters, ... figure if we can have both a hidden and favorite app,... And figure how to show the excluded apps, maybe a password or in the preferences or both. 

I think that this feature should be worked on, still. We have already discussed that this is what should be done in order to get an exclude button that is in at least some working shape.

The questions that we need to ask are:

1. How are the apps, shortcuts, and contacts filtered? 
2. How are the favorites filtered and saved?
3. Is there a way to show hidden items in the settings?

**Comment by TBog** [comment]
Can you give me a use case for hidden items?
Do you want to hide the Literotica or PornHub app?

Can we have a global toggle for showing the hidden apps? Like in the main context menu? Or in preferences?
This way I don't have to add a preference with all the hidden items, I can just show them when the toggle is on and maybe add a QuickList filter to find them easily. We can have an eye symbol with a strike-through ( ~~👁 strike-through is like this~~ ) on the icon to show it's hidden.

**Comment by HunterArmstrong** [comment]
> Can you give me a use case for hidden items? Do you want to hide the Literotica or PornHub app?

Hiding the PornHub app wasn't my original thought. I have the Samsung secure folder for that stuff 😉. 

No. The main apps I would want to exclude are apps that are either not usable/ used (Call Filter, Digital secure, Samsung Tips) or not a go to app for something another app is used for (Samsung internet, Gallery)

> Can we have a global toggle for showing the hidden apps? Like in the main context menu? Or in preferences

I'm thinking maybe something in the quick list? The quick list is customizable and maybe the hidden items list can be either put on or taken off of the quick list.

> We can have an eye symbol with a strike-through ( ~~👁 strike-through is like this~~ ) on the icon to show it's hidden.

This is a great idea and may work. But the final product in question may need to be discussed more to work out how it's going to look and how it's going to function. If you have previews of what you are thinking of I'll be more than happy to be the one you can bounce ideas off of. 🙂🙂

**Comment by HunterArmstrong** [comment]
Have we figured out a toggle yet?

**Comment by TBog** [comment]
My solution as of now is to add a Hidden category for apps, like we have the Favorites now. And add an option in the main context menu to toggle the visibility of the hidden apps from the usual actions.
I'll also add an action to show the hidden apps no matter the menu toggle

**Comment by HunterArmstrong** [comment]
Seems Legit.👍🏻👍🏻

**Comment by HunterArmstrong** [comment]
Hey, I just thought of a couple questions

- Are we able to look up apps in the hidden category from the search bar?

- Are the shortcuts from apps going to be hidden from search as well?

**Comment by TBog** [comment]
1. Right now I can't filter based on category. This means we can't search in Favorites or in Hidden. 
2. Shortcuts are handled independently of apps. I don't see why you would want to hide a shortcut, you can unpin / remove it.

**Comment by HunterArmstrong** [comment]
> 1. Right now I can't filter based on category. This means we can't search in Favorites or in Hidden. 

So, does this mean that apps that are put into the hidden apps folder wont pop up into the search results list when you type the name in?

> 2. Shortcuts are handled independently of apps. I don't see why you would want to hide a shortcut, you can unpin / remove it.

I was wondering because I already had shortcuts from apps whose icon I may not tap on if I had shortcuts put up in TB and felt that if I hid an app, I may hide a lot of shortcuts on accident

> Edit: I can add the ability to hide shortcuts, just like you can add them to the favorites, but why? 

What you said about hiding shortcuts is exactly right. I never intended of putting you through that type of work when I or someone else could have just deleted the shortcut. Lol

**Comment by TBog** [comment]
> > 1. Right now I can't filter based on category. This means we can't search in Favorites or in Hidden. 
> 
> So, does this mean that apps that are put into the hidden apps folder wont pop up into the search results list when you type the name in?

That is not what I meant.
Of course the hidden apps will not show in the results, or else what's the point of hiding them?
What I meant was that you can't search in the hidden apps list, just like now you can't search in the Favorites

**Comment by HunterArmstrong** [comment]
But wait, I can search from the favorites list just fine. Are you saying that you wouldn't be able to search from the favorites list as well in the new update?

**Comment by TBog** [comment]
Not what I meant.
Now you can't search in the Favorites.
More explicitly when you search, the results may include Favorites, but you can't search exclusively in the Favorites category.

**Comment by HunterArmstrong** [comment]
Gotcha. 👍🏻👍🏻 Hope nothing bad happens.🤞🏻🤞🏻

**Comment by TBog** [comment]
fixed in e09060b3681a608fd95ee8c727baef3c8e6389d2
The way I finally implemented it hides the app from the search result but not the actions in the QuickList

**Comment by HunterArmstrong** [comment]
> fixed in e09060b3681a608fd95ee8c727baef3c8e6389d2
> The way I finally implemented it hides the app from the search result but not the actions in the QuickList
> 
> This is how it looks when viewing all apps with one calendar hidden and one not. 
> ![Screenshot_20200914-175901_TinyBit launcher.jpg](https://user-images.githubusercontent.com/6465804/93102435-2c89dc80-f6b4-11ea-978d-33df415e6387.jpg)

Looks good M8
