### ISSUE TITLE
[FEATURE] drag&drop for QuickList

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#39]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to re-order the items from the QuickList and the only way to do so is to remove then add them in the desired order.

**Describe the solution you'd like**
I'd like to be able to drag and drop the icons in the "Customize QuickList" dialog where right now the only possibility is touch to remove.

**Comment by HunterArmstrong** [comment]
Yeah. This is a good idea here cheif.
