### ISSUE TITLE
Cannot edit search hints

### ISSUE THREAD

**Issue by opk12** [TBog/TBLauncher#391]
# Description #
I cannot edit any search hints.

## Steps to Reproduce ##
To reproduce the behavior:
1. Open the settings.
2. Go to `Layout`.
3. Go to `Edit search hint`.
4. Long-tap on a hint.
5. Tap `Rename`.
6. Nothing happens.

## Expected behavior ##
Tapping `Rename` should let me edit the search hint.

## Device info ##
Android 7.1 from Samsung. TinyBit 7.3 from F-droid.

**Comment by TBog** [comment]
You're right. I'll try to debug this today.
