### ISSUE TITLE
On Enter, wait for filter to complete, then start first app

### ISSUE THREAD

**Issue by ltguillaume** [TBog/TBLauncher#402]
# Description #

Whenever I want to start an app, I type in 2 letters and press Enter on the keyboard. I know beforehand which app is the first (well, visually the last) in the result list and as such should be started when pressing Enter.

However, I find that if the list reorganizing is still busy (I'm not sure of the reason, perhaps because of the animation, perhaps because of the filtering process itself) when I press Enter, _another_ app starts.

As an alternative explanation, it might also be that the filter misses out on the _first_ letter I type, immediately after the keyboard shows, but I think that's less likely.

## Steps to Reproduce ##

To reproduce the behavior:
1. Optionally turn on Battery Saver to slow down the device a bit
1. Go to Search
1. Type in a few letters and press Enter quickly after
1. See another app started, instead of the app that should be started according to the result list

## Expected behavior ##

The first result (visually last in the list) should be started consistently.

## Device info ##

  OS: Android 11
  TinyBit Launcher version: 7.4 (and I believe 7.3 as well)

**Comment by TBog** [comment]
If the animation started the list has already changed so pressing enter will start according to the new list.
I think a better fix would be to let the user disable the animation. Do you agree?

**Comment by ltguillaume** [comment]
No? I don't think animations should in any way influence how the query works, which in turn means that that they shouldn't have to be disabled to have a reliably working filter process.

**Comment by TBog** [comment]
I'm not sure how you expect me to fix this?
At what point during the animation do you expect to switch from the previous result list to the new one?

**Comment by ltguillaume** [comment]
I don't really care about the animation, but I would say directly. The thing that's bugging me isn't the animation at all: I just think that the action "pressing Enter" should reliably use the result list based on _all_ the letters typed before pressing Enter, no matter in what phase the animation might be.

**Comment by TBog** [comment]
I have misunderstood. What you expect is to wait for the search to finish before launching the result.

**Comment by TBog** [comment]
I'm not sure if I can leave the fix as is. I'm thinking of adding a check to see if the time between the `[Enter]` and the launch is too long.

**Comment by ltguillaume** [comment]
> I'm not sure if I can leave the fix as is. I'm thinking of adding a check to see if the time between the `[Enter]` and the launch is too long.

The time between `[Enter]` and the launch is not relevant to this problem. During this time, the search results shouldn't have changed, and if they were (e.g. `ab` `[Enter]` `c`), then the newer search result should not matter for what app is launched.

I'm not sure why your code is related to the list adapter. Are you manipulating the adapter directly, or are the search results put into an array first?

My thoughts would be, simply put:

Key pressed: `a` =>
1. `currentResultsQuery = false`
2. Do the search
3. `currentResultsQuery = "a"`

Key pressed: `b` =>
1. `currentResultsQuery = false`
2. Do the search
3. `currentResultsQuery = "ab"`

Key pressed: `[Enter]` =>
1. `launchFirstQuery = currentSearchFieldValue`
1. `If (launchFirstQuery = currentResultsQuery) launch(resultsList[0])`
1. `Else`
1. `currentResultsQuery = false`
1. search(launchFirstQuery)
1. `currentResultsQuery = launchFirstQuery`
1. `If (currentResultsQuery = launchFirstQuery) launch(resultsList[0])`

**Comment by TBog** [comment]
ab [Enter] c
This should not happen or else the app that's launching would be unexpected.
You should not be able to add search parameters after pressing Enter.

The current implementation will cancel the ab search without getting the results (even if you've pressed Enter) and start a new search for abc
This is because searching is a CPU and memory intensive operation and you don't want to do it if you don't intend to use the results

**Comment by ltguillaume** [comment]
> ab [Enter] c This should not happen or else the app that's launching would be unexpected. You should not be able to add search parameters after pressing Enter.

Yeah, I assumed this shouldn't happen, which is why my pseudocode didn't account for it either, but I only brought it up because you said there could be something going on in
>the time between the [Enter] and the launch

I guess I still don't understand what could happen there then, and why you'd need to check this.

> The current implementation will cancel the ab search without getting the results (even if you've pressed Enter) and start a new search for abc This is because searching is a CPU and memory intensive operation and you don't want to do it if you don't intend to use the results

That makes sense, of course, but I think the issue at hand can only occur in the following situations:

1. Somehow the search for the incomplete string isn't canceled and gets used when pressing `[Enter]`
2. The first letter of the query isn't registered, so instead of `ab`, they search is only for `b`.

**Comment by TBog** [comment]
> > the time between the [Enter] and the launch
>
> I guess I still don't understand what could happen in that time frame then, and why you'd need to check this.

I was talking about the wait I added.
Let's say you search for `ab` and then press `[Enter]` but because the phone is slow it takes a second. In the mean time you get impatient and put the phone on the table. When the search finishes the app (video/music app) opens and loud music fills the room.

**Comment by ltguillaume** [comment]
I think in that unlikely scenario, the only reason the app maybe shouldn't start is if the user turned off the screen. And acrually I would still want it to. In the specific situation you're describing I would most definitely still expect the app to be launched. In summary, I wouldn't pollute the code with any timeout for that.
