### ISSUE TITLE
Google Clock widget doesn't resize correctly 

### ISSUE THREAD

**Issue by urmomseksy** [TBog/TBLauncher#403]
# Description #
When adding the digital clock widget for the Google Clock app, the widget doesn't resize the text correctly. The text is huge and you cannot see the whole widget.

## Context ##
The widget works correctly on KISS Launcher. Other widgets I've tried on TinyBit seem to work correctly.

## Steps to Reproduce ##

1. Install Google clock (not FOSS: https://play.google.com/store/apps/details?id=com.google.android.deskclock)
2. Choose to add digital clock widget (either transparent or solid option)
3. Resize widget 
4. Widget text doesn't fit to screen

## Expected behavior ##
Widget text should scale or zoom correctly as it works on all other launchers I've tried.

### Screenshots ###
KISS launcher screenshot: https://i.postimg.cc/C5VbG2qn/Screenshot-20230906-054659-KISS-launcher.jpg

TinyBit launcher screenshot: https://i.postimg.cc/tTD9kZ1d/Screenshot-20230906-054748-Tiny-Bit-launcher.jpg

(Images will expire in 31 days)

## Device info ##

  * Device: Samsung Galaxy  A53 5G
  * OS: Android 13
  * TinyBit Launcher version: v7.4

**Comment by TBog** [comment]
duplicate of #342

**Comment by urmomseksy** [comment]
I'll close this then. Thanks.
