### ISSUE TITLE
[search] No result list after deleting search query

### ISSUE THREAD

**Issue by opk12** [TBog/TBLauncher#414]
# Description #

When I type something in the search bar, I change my mind and delete what I typed, I end up with no result list.

## Context ##
`Behaviour` - `Desktop mode <<Search>>` - `Initial result list` is set to `Adaptive history`.

## Steps to Reproduce ##
1. Type something in the search bar.
2. Delete what was typed.
4. See that there is no result list.

## Expected behavior ##
The adaptive history should appear again.

## Device info ##

  * Device: Samsung
  * OS: Android 7.1
  * TinyBit Launcher version: 7.4 from F-droid

**Comment by TBog** [comment]
This is the expected behavior.

**Comment by opk12** [comment]
Ah sorry then. I started using the app recently and couldn't think of a use case for ending up with the black background in the place of the list. But I don't really care - it's rare and minor, and effectively cosmetic, as I can reset with the Home button. I can't find where to click to untoggle the `bug` label, maybe this should be closed and let another user reopen if they are interested?

**Comment by TBog** [comment]
You can add a history button to the dock
