### ISSUE TITLE
Feature Request: Use Accent Color On Scrollbar

### ISSUE THREAD

**Issue by Saijin-Naib** [TBog/TBLauncher#416]
**Description**
I think it would be nice for both theme and visibility if the scrollbar widget got the accent color defined in User Interface. 

**Solution**
Have this item inherit the accent color. 

**Alternative solutions**
Perhaps use a lighter or darker (material?) shade of the accent color. 

**Additional context**
Launchers like Quickstep also do this.

**Comment by TBog** [comment]
The scrollbar for the result list is getting its color from the result list `Touch Color`

**Comment by Saijin-Naib** [comment]
I'm sorry for the noise 😑
