### ISSUE TITLE
widgets that have a customization prompt don't work

### ISSUE THREAD

**Issue by pine-serpent** [TBog/TBLauncher#461]
# Description #
When trying to add a widget that has a popup customization prompt they simply to don't work and never offer the prompt.

## Context ##
Example is the Antennapod widget. Normally when adding this widget a full screen option prompt opens so tiu can select opacity, buttonzns.

## Steps to Reproduce ##
1. Hold on widget screen.
2. Tap add widget.
3. Select antennapod widget.
4. Nothing happens.

## Expected behavior ##
Expect full screen widget options to popup.

## Device info ##
  * Device: pixel 5q
  * OS: android 14
  * TinyBit Launcher version: 7.4

**Comment by pine-serpent** [comment]
also fails to work with the home assistant companion app.

**Comment by TBog** [comment]
I think this only happens on Android 14
Not sure why but the request to open the configuration / customization for the widget returns with "cancel". I've found a way around it but I'm not yet sure if this is the intended behavior.

**Comment by TBog** [comment]
Found the reason. https://developer.android.com/about/versions/14/behavior-changes-14

> For apps targeting Android 14 (API level 34) or higher, the system further restricts when apps are allowed to start activities from the background:

> When an app sends a PendingIntent using [PendingIntent#send()](https://developer.android.com/reference/android/app/PendingIntent#send(android.content.Context,%20int,%20android.content.Intent,%20android.app.PendingIntent.OnFinished,%20android.os.Handler,%20java.lang.String,%20android.os.Bundle)) or similar methods, the app must opt in if it wants to grant its own background activity launch privileges to start the pending intent. To opt in, the app should pass an ActivityOptions bundle with [setPendingIntentBackgroundActivityStartMode(MODE_BACKGROUND_ACTIVITY_START_ALLOWED)](https://developer.android.com/reference/android/app/ActivityOptions#setPendingIntentBackgroundActivityStartMode(int)).

I'm not sure why the configuration intent needs it, but this fixes the problem:
https://github.com/TBog/TBLauncher/blob/54b24d0f1b1527dd5bf9e1d67563f7d92b2ae492/app/src/main/java/rocks/tbog/tblauncher/widgets/WidgetManager.java#L655-L667
