### ISSUE TITLE
Moving widgets on upper and lower pages.

### ISSUE THREAD

**Issue by t-e-s-tweb** [TBog/TBLauncher#466]
# Description #
When you add additional pages from layout > wallpapers > pages, up and down double pages then moving widgets to upper and lower screens are available options but moving to upper and lower left and right are not available like middle screen where you have option to move to left screen or right screen. 

## Context ##
Moving widgets to upper and lower keeps then in the middle screen only. the left and right of upper and lower are empty and manually moving them doesn't work it just puts then back again in the middle. 
## Steps to Reproduce ##
1. enable upper and lower pages from Layout > wallpaper > pages
2. add a widget. 
3. Move it to upper screen by long click and move to up screen. 
4. Try to move it to left or right side. 
5. the widget resets back in the middle. 

## Expected behavior ##
Widget should be able to move to left and right screen like it is when moved to left and right from the middle screen. 

### Screenshots ###
As shown the the image, these locations are available but moving widgets to those doesn't work. 

![IMG_20240513_134242_995](https://github.com/TBog/TBLauncher/assets/16269572/aeef152f-6448-47f6-99ac-45d87611d174)

## Device info ##

  * Device: Mi 10T
  * OS: Android 12 MiUi 14.5
  * TinyBit Launcher version: 7.5

**Comment by TBog** [comment]
I believe this is intended behaviour
