### ISSUE TITLE
[FEATURE] Ability to pick images from storage for icons.

### ISSUE THREAD

**Issue by Invisible3ck** [TBog/TBLauncher#47]

**Comment by TBog** [comment]
1. Please choose a single feature request per issue.
2. What custom image are you looking to pick? From the gallery?
3. Background blur is something I can't do if the user is using a LiveWallpaper

**Comment by Invisible3ck** [comment]
Alright, let's go with custom image. Yes, I would like to pick a custom image from my phone's storage via gallery or file explorer. Whichever one is possible.

**Comment by TBog** [comment]
Choosing an image from storage is tricky. The user should be allowed to crop / resize it and this adds a lot of UI that I'm not comfortable with.
This is not impossible but I'll leave it for later.

**Comment by TBog** [comment]
I added the ability to choose any icon from an icon pack.
Also icon scale, background color and shape are customizable.
@Invisible3ck try it out in release [v4.7-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v4.7-dev.1) and tell me if you still think picking from storage is desired.

**Comment by Invisible3ck** [comment]
> I added the ability to choose any icon from an icon pack.
> Also icon scale, background color and shape are customizable.
> @Invisible3ck try it out in release [v4.7-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v4.7-dev.1) and tell me if you still think picking from storage is desired.

That’s a nice feature set. I still wish to pick a custom image from storage if possible please.

**Comment by Invisible3ck** [comment]
@TBog Hi. How is the progress going with this request? Just curious.

**Comment by TBog** [comment]
I'm sorry, I'm not working on this. Feel free to submit a PR.
Right now I'm struggling with switching from ListView to RecycleView and improving the scroll of the list. Sometimes the result list scroll resets when renaming or editing tags.

**Comment by victor0d** [comment]
Only a suggestion, that could be much easier to implement: Forcing the user to choose a image that he/she will edit previously according to a predefined size/aspect-ratio/format. If it is not correct, the launcher will refuse to import it (with an error message).

Obviously the user has to be informed previously about the size/aspect-ratio/format required.

**Comment by victor0d** [comment]
- Fair enough TBog. You have a point.
-- Some Gallery Apps have support for it. Although it is true that not all of them.
-- I have just tried the two galleries that I have installed in my phone: Simple-Gallery and AOSP-ROM-Gallery, and, the first one will allow me to specify everything, but the second one only aspect ratios.
-- The main reason to suggest this, was having an option to do it, without increasing the load in the code and longer term support.
-- A basic user guide or through forums, could suggest some apps that could help the user to do that job.
- At the end of the day, I completely agree with you that adding external libraries will increase the building load and issues with dependencies. Better avoid that road.

**Comment by TBog** [comment]
feature added with commit 922657a539bf57d0a140d6d22f2fb5a6c86f8ed3

**Comment by victor0d** [comment]
What road did you decided to take for this feature ?

**Comment by victor0d** [comment]
Actually it was the one that looked better of all those that you proposed and anything else that I manage to find.
You are amazing man.

**Comment by victor0d** [comment]
This feature is working now (v6.10(32)). Very cool TBog.

Nevertheless, I would like to suggest to extend the option to Tags and Shortcuts. Right now it is only possible with Apps.

**Comment by TBog** [comment]
> Nevertheless, I would like to suggest to extend the option to Tags and Shortcuts. Right now it is only possible with Apps.

fixed in 6f65ca2c424aa945b721d39ad9107ca415af0fc9

**Comment by victor0d** [comment]
Thank you TBog.
