### ISSUE TITLE
[FEATURE] Search bar hint setting

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#58]
**Is your feature request related to a problem? Please describe.**
For this feature, I think it would be cool to be able to customize the hint text in the search bar

**Describe the solution you'd like**
Custom search bar text that is either:
- the default text
- one custom message
- one random message out of multiple messages
- or nothing at all

**Describe alternatives you've considered**
N/A

**Comment by TBog** [comment]
fixed in 07b5e0b985421d3d79611ec650ac8cf57aff330c
