### ISSUE TITLE
[FEATURE] Change Background Color and Transparency of shortcut

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#60]
**Is your feature request related to a problem? Please describe.**
When I add a white icon with a "transparent" background to TB with the circle icon frame, I did not expect to see it turn White on white. So now I just have a white circle for an icon

**Describe the solution you'd like**
A customizable background color for shortcuts.

**Comment by TBog** [comment]
I'm not sure what you mean. Can you please write the steps I need to take to get the white circle?
Are you changing the icon of an application? a shortcut? an Action? a Tag?
What Icon Pack is the icon with transparent background from? Or maybe it's not an icon pack?

**Comment by TBog** [comment]
> **Describe the solution you'd like**
> A customizable background color for shortcuts.

On a per-shortcut basis or a general color for all shortcuts?

**Comment by HunterArmstrong** [comment]
As a general Background Color for all shortcuts

**Comment by HunterArmstrong** [comment]
> I'm not sure what you mean. Can you please write the steps I need to take to get the white circle?

1. With a shortcut maker app, Create a shortcut to home screen with an icon from the Whitcon Icon Pack
![Screenshot_20201124-145328_Shortcut Maker.jpg](https://user-images.githubusercontent.com/57189836/100161153-c1077c80-2e65-11eb-89f8-e8a2a540b0c1.jpg)
2. Look up shortcut you made using the search tool
![Screenshot_20201124-145442_TinyBit launcher.jpg](https://user-images.githubusercontent.com/57189836/100161173-ca90e480-2e65-11eb-97d3-5fa19d95cfb4.jpg)
3. See Result

> ~~Are you changing the icon of an application? a shortcut? an Action? a Tag?~~
> ~~What Icon Pack is the icon with transparent background from? Or maybe it's not an icon pack?~~
> 
> Now I saw you mentioned a shortcut, you can change the appearance of shortcut icons from the settings.
> 
> `User interface`🔸`Icon pack`🔸`Shortcut icon shape`
> * If you choose a shape it'll have a white background with that shape.
> * If you choose **System default** it will have a transparent background.

**Comment by TBog** [comment]
I have removed the background color when the icon is only cropped and not scaled.
Can you please test my de release [v4.7-dev.1](https://github.com/TBog/TBLauncher/releases/tag/v4.7-dev.1) and give feedback or close this issue?
