### ISSUE TITLE
[BUG] Installed apps on phone disappear from app list

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#65]
**Describe the bug**
After a recent update of my phone a majority of the apps I have had installed on my phone including the icon pack(which makes the icon pack not accessible) have all suddenly decided to not show up on TB

**To Reproduce**
1. Probably give your phone a system update
2. After restart, Click on apps in quick list
3. See error

**Expected behavior**
You should see the majority of apps that you installed to show up in the app menu including the icon pack

**Screenshots**
![Screenshot_20201210-105043_TinyBit launcher.jpg](https://user-images.githubusercontent.com/57189836/101816217-9b20df80-3ad5-11eb-83a9-eb4ba2bb0f93.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S10+]
 - OS: [e.g. Android 10]
 - Version [e.g. v4.5]

**Additional context**

**Comment by TBog** [comment]
> 2. After restart, Click on apps in quick list
> 3. See error

What error is that?
Are apps missing from the app list or from the QuickList? 

The only changes that may affect you was the way the shortcut ID was generated. If you give me a backup of your settings I should be able to fix it the shortcuts missing from the QuickList.

**Comment by HunterArmstrong** [comment]
The error was in the app menu.

**Comment by HunterArmstrong** [comment]
Here's the [backup](https://drive.google.com/file/d/1Hw6s47K3NGtp-C1knPHjFq17MQyyYsOj/view?usp=drivesdk) of the applist

**Comment by TBog** [comment]
@HunterArmstrong Now that I'm on the PC I can see in the screenshot you provided the loading animation has not stopped. I'm talking about the rotating squares on the bottom left.
This means that some background services (the loading of the apps, contacts and shortcuts) have not finished or have crashed. I need more info to debug this.

Could you send a [logcat](https://developer.android.com/studio/command-line/logcat) or [bug report](https://developer.android.com/studio/debug/bug-report)?
If you don't know how, look [here](https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/) for details on bug reporting or get a [logcat via Android Studio](https://help.testlio.com/en/articles/129738-how-to-get-logs-from-your-android-device)

**Comment by HunterArmstrong** [comment]
[Here's the bug report from my Drive](https://drive.google.com/file/d/1IX6TYvKSb6ibpZhdSqt7kknEgOjlNMJx/view?usp=drivesdk)

**Comment by HunterArmstrong** [comment]
Sorry about the access stuff

Just unlocked it for you right now.

**Comment by HunterArmstrong** [comment]
Have you figured out what the problem was?

**Comment by HunterArmstrong** [comment]
So, as of right now I just recorded a [logcat](https://drive.google.com/file/d/1IxWYKMNIWFhd9puGo_gr3VsCkyVkxn4Y/view?usp=drivesdk)of me uninstalling and reinstalling the Launcher just in case if you can't really find out what the issue is.

**Comment by HunterArmstrong** [comment]
Just accepted the requests for access.

**Comment by HunterArmstrong** [comment]
So, nothing wrong?

**Comment by TBog** [comment]
It seems like you are logged in on a different user that has only 20 apps.

**Comment by HunterArmstrong** [comment]
How do I log in as myself?

**Comment by TBog** [comment]
I'm not sure how. Samsung kind of disabled the standard work profile.
Did you install any app that adds users or work profiles? Like [Shelter](https://github.com/PeterCxy/Shelter)?

**Comment by HunterArmstrong** [comment]
No. None that I know of

**Comment by HunterArmstrong** [comment]
As of right now i have

done the whole factory reset on my phone. 
Uninstalled and reinstalled TB as well as clear all the cache data and normal data
Deleted The Secure folder app and the backups
Turned off Work Profile

And the apps i have installed are still not popping up in the app list

I highly doubt that there are other profiles that may say that i have 20 apps right now. But, i may be wrong. Do you think that this is just a dumb bug? A Virus? Or is this just Samsung denying other launchers the ability to work properly?

I never saw this happen with KISS Launcher though. which is strange because i think that there are settings on KISS  that also apply to TB.

If you have any Ideas. Please give me all of them. because i think i just ran out. :(

**Comment by TBog** [comment]
Would you please try different versions of TBLauncher?
You can find them [here](https://github.com/TBog/TBLauncher/releases)
If you find on which version it works and on which it does not we can look at the differences.

Are the squares in the bottom left of the screen always rotating? They should rotate only while the launcher if loading the apps, contacts and shortcuts. If you touch that icon the loading should restart.

Right now I can't replicate your problem and the logs don't show any error.

**Comment by HunterArmstrong** [comment]
None of the old versions work.
