### ISSUE TITLE
[BUG] TinyBit Launcher not showing all apps

### ISSUE THREAD

**Issue by anthonymvicente** [TBog/TBLauncher#68]
On first launch of the launcher, it doesn't seem to have "access" to all my apps. The default quicklist icon to filter apps only shows a handful (~15 or so), and searching for apps I know I have installed (eg Spotify) returns no results. This is on a fresh install of the launcher, no settings changed.

**To Reproduce**
1. Install the app? As mentioned above, it just seems like right out of the box behavior on my phone.

**Expected behavior**
Either through the app filter or by searching, I expect to have some access to all my apps through the launcher.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - Version: TinyBit Launcher 5.1

**Additional context**
If there's anywhere I can look to provide more info please let me know, I know there's not a lot to go on here.

**Comment by HunterArmstrong** [comment]
That is the same stuff happening with me!!!!

**Comment by TBog** [comment]
> On first launch of the launcher

Does it work normally on the second launch?

Is this happening with older versions too?

**Comment by anthonymvicente** [comment]
> 
> 
> > On first launch of the launcher
> 
> Does it work normally on the second launch?

Yes, sorry the "On first launch" may have been misleading, I meant it has the issue from the start, it continues to not show all of my apps when I keep trying.

> 
> Is this happening with older versions too?

I tried 5.0, which had the same issue, and 4.7, which actually showed even fewer apps (Only showing the "Settings", "Play Store", and "TinyBit Launcher" apps). These were all installed from F-Droid

**Comment by TBog** [comment]
Is this happening with older Android versions? You said you had Android 11. I only tested until 10.

**Comment by anthonymvicente** [comment]
> 
> 
> Is this happening with older Android versions? You said you had Android 11. I only tested until 10.

I'm only running Android 11, so I haven't been able to test on Android 10.

**Comment by TBog** [comment]
Do you have the same issue with KISS or HG Launcher?

**Comment by TBog** [comment]
I tested on the emulator with Android 11 and only got 5 apps. I think I have a workaround but further investigation is required.

**Comment by anthonymvicente** [comment]
> Do you have the same issue with KISS and HG Launcher?

Sorry for the delay, I tested with KISS and HG Launcher and did not run into the issue, but showed all my apps. Please let me know if there's anything else I can do or info I can provide to help.

**Comment by HunterArmstrong** [comment]
I think you might have to send in a LOG

**Comment by TBog** [comment]
> Please let me know if there's anything else I can do or info I can provide to help.

Like I said, I have a way to replicate the issue, just not a fix. Thanks for the information you provided. The Android 11 is doing something different with my application collection code. 

The strange thing is that code is not changed from KISS.

**Comment by TBog** [comment]
fixed in commit db21b23738b2c7ddf78d48ffc55ffdea1cd29a5c
build can be found [here](https://github.com/TBog/TBLauncher/releases/tag/v5.3)

**Comment by anthonymvicente** [comment]
> 
> 
> fixed in commit [db21b23](https://github.com/TBog/TBLauncher/commit/db21b23738b2c7ddf78d48ffc55ffdea1cd29a5c)
> build can be found [here](https://github.com/TBog/TBLauncher/releases/tag/v5.3)

This worked, thank you for the quick fix!

**Comment by HunterArmstrong** [comment]
Works for me as well👍👍
