### ISSUE TITLE
[FEATURE] show Quick list in Gestures actions list

### ISSUE THREAD

**Issue by ildar** [TBog/TBLauncher#69]
The "Fling up/down/..." misses the action: "Show Quick list" (without the search bar).

**Comment by ildar** [comment]
Sidenote on the "Quick list" UX: I do like it and use it most frequently (in KISS currently). But I am sorry, it looks out of place.

Maybe it's better discussed somewhere else or should I open another issue (?)

Details:
1. as it is the "Quick list", it should be rapidly available. As I wrote already, I think TBL is gorgeous so I understand why there's no "Show always" option.
2. It is tied to the search bar. That's also unfortunate. I just got the idea that (a) tap could show the Quick list and (b) "Filng up" would show the Search bar. Are you ready to reconsider the UX? :-) 
3. "Quick list" is more a "Quick bar" maybe? ;-)

**Comment by TBog** [comment]
I know right now, without a wiki or tutorial, it's hard to know sometimes what we're talking about so let me explain.
There are 2 display modes right now (I want to add an 'Empty' display soon). The "Search" (with the search bar, result list, quick list) and the "Widget" (with at most 3 screens of widgets)

Now let me ask this, should the "Show always" option display the Quick-List in the widget display mode?

**Comment by ildar** [comment]
Exactly in "Widget mode", thanks.

I'm no a UX expert, not even close. So just sharing my thoughts here:
1.  I like your division to three "modes". One thing I miss here is "how to
customize them" to get the appearance I want. Yes, I'm mostly looking for
the "classic KISS" widget+Quick bar currently.
2. After reading your comment I surprisingly found that Empty mode can be
"emulated" by the Widget mode with widgets on the side screens. I wont mind
trying this ))) Just a note though.

I fairly hope you have a broader vision on TBL UX and you'll implement
everything right ))

**Comment by TBog** [comment]
The empty middle screen of the "Widget" mode seems like a workaround, that's why I wanted to add the "Empty" mode. I did the same thing with my widgets until I figured out I always scrolled to access the Bubble widget so I moved it to the middle. Now I kinda want to have separate gestures to open the 3 nodes and have the "Empty" one as a default when pressing the home button.

**Comment by TBog** [comment]
Do you still want to have the Quick List toggle as an action for gestures?

**Comment by ildar** [comment]
Just tested a recent version and see there's no use case left for this.
Thanks a lot!
/close
