### ISSUE TITLE
[FEATURE] Contrast adjustment for icons

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#70]
**Describe the solution you'd like**
Librechair sports a great little feature that allows for an easy "softening" of all icons: it allows to reduce the contrast of all the icons on the homescreen and in the app drawer. Since most current icons are very bright and with high contrast, they do not blend well with dark themes. As such, this adjustment feature would be very welcome in TBLauncher, too. Also, monochrome icon packs like Whicons greatly benefit from a reduced contrast (in this case it would reduce the brightness).

**Comment by TBog** [comment]
This can be done and it's a great idea.
I think I'll have different levels of softness for the 
  * [] result list
  * [] quick list

**Comment by ltGuillaume** [comment]
I guess it will cause a delay, yes, but as long as the filter isn't a complicated algorithm with lots of possibilities it should be all right. I suppose a test method that calculates the system time difference after the result list is triggered and after the result list is shown is effective enough to see the impact. I'll test and post the logcat output if you'd like.

**Comment by TBog** [comment]
Should we also add hue and saturation?

**Comment by TBog** [comment]
Preview [build](https://github.com/TBog/TBLauncher/releases/tag/v5.4-contrast.1)

**Comment by ltGuillaume** [comment]
This is great! Works like there's no delay.

As for hue and saturation: unless it would introduce performance issues, I think it'd be quite a distinguishing feature for TBLauncher, especially if the hue could be used to "colorize" (as in any image editor: set the color of the entire icon to a certain color).

**Comment by TBog** [comment]
Added saturation, hue and scale (to facilitate inverting colors). Here is the preview [build](https://github.com/TBog/TBLauncher/releases/tag/v5.4-contrast.2)

Can we close this issue like this or is anything else missing?

**Comment by ltGuillaume** [comment]
I think this is great and even more I could hope for. Thank you!

I just found two elements that are still green though: when double-clicking the text in the search bar, so it's selected, (1) the background is green and (2) the "selection thumbs" are bright green.

**Comment by TBog** [comment]
> I think this is great and even more I could hope for. Thank you!

You're welcome. I think I'll add a preview before closing. 

> I just found two elements that are still green though: when double-clicking the text in the search bar, so it's selected, (1) the background is green and (2) the "selection thumbs" are bright green.

Not related to this issue, right?

**Comment by ltGuillaume** [comment]
Sorry, you're totally right. But I see that you already added this to the issue that _is_ related 👍
