### ISSUE TITLE
How to dial a number? What is a shortcut? What does the chocolate (9-square) menu button do?

### ISSUE THREAD

**Issue by adjenks** [TBog/TBLauncher#74]
1. I can add the telephone app to my quick list, but I thought that you'd be able to add some sort of feature to just call the number that you've entered into the search bar, no? Do I have to open the telephone app? This app says it requires the permission to make calls, is the permission not for initiating calls quickly?
2. Under the actions section, there are "shortcuts", you can add them to your quick list and they are represented by 3 dots and a line skipping from the first to the last. When I tap on it it presents an empty box, so my question is, how do you create shortcuts and what type of shortcuts are they?
3. The chocolate (9-square) menu button on the left of the search bar, what does it do? When I click on it all it does is make the entire interface blink for a split second.

**Comment by TBog** [comment]
1. I have not ported the call feature from KISS yet. The permission will be needed for this, you're right.

2. For example in Chrome you tap the three dots then select `Add to Home screen` 
Or you can use the [Shortcut maker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker) app to make shortcuts. What Android version do you have?

3. The button on the left of the search bar currently reloads all providers (Apps, Contacts, Favorites, ...)
This is a placeholder action. It will be possible to choose an action as is currently possible for the gestures.

**Comment by adjenks** [comment]
1. I can already call a contact by tapping the phone next to their name in TBLauncher, it works fine. Are you saying that it's not supposed to work? It asked me for permission once, and now it works fine, I just can't specify a number dynamically.
2. Oh okay, I found the equivalent feature in FireFox "Add to Home screen". I'm using Android 10.
3. I think in its current state the button just leaves me wondering what it does. If you make it do anything more than "blink" then you wouldn't have to get rid of it. I was sort of expecting it to fall back to the traditional pile of app icons. Although that's against the paradigm of this app, I find the pile of icons useful when I forget the name of what I'm looking for and I have to recognise the icon to find something. The long list of apps that appears in the "applications filter" isn't good for that because it only shows 1 icon and lots of text, which is poor for quick visual scanning. In the end it's your choice, but my vote would be to make it show the pile of icons to help me when I forget the name of something. Or maybe just tuck that feature somewhere else and use this button to bring up the number pad for a telephone. That was my second guess as to what it was supposed to do, I thought maybe it was symbolically representing a phone pad, but I guess that symbol would have an extra row of squares. I'd be happy with that too, since it is a telephone it should be easy to make calls.

**Comment by TBog** [comment]
Thanks for the information. 
1. Add the grid list and the number pad as possible actions.
2. Add the phone provider from KISS

**Comment by adjenks** [comment]
Sounds like a good plan. Looking forward to it all.

**Comment by TBog** [comment]
I'll close this issue after the grid result is merged even tho' I was thinking of adding some features from "Shortcut maker". If anyone is interested in those features please make a separate feature request.

**Comment by adjenks** [comment]
Thank you for your hard work!

**Comment by adjenks** [comment]
Oops. I hit the wrong button. I meant to just comment, you can close it when you're ready. Hahaha. Have a nice day.

**Comment by TBog** [comment]
have you tested the PR? Do you need a dev build?

**Comment by adjenks** [comment]
I have not. I suppose I could test it on my old phone if you'd like me to test it. I would need a build I don't currently have an android build environment set up.

**Comment by TBog** [comment]
Try [this](https://github.com/TBog/TBLauncher/releases/tag/v6.8-test.1) test release

**Comment by daffydock** [comment]
Hi @Tbog, tried the test release. Tested with a random contact number and it worked great. Cheers, and Happy Holidays.

**Comment by ltGuillaume** [comment]
Can I change the icon that's next to a number-to-be-dialed?

**Comment by TBog** [comment]
implemented custom icon for number-to-be-dialed in 48393d78c7959b76e83d9064f4fd3e7a9f7ed558
