### ISSUE TITLE
[FEATURE] Option to scroll wallpaper up and down as well as left and right

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#78]
**Is your feature request related to a problem? Please describe.**
After finding out that you can make widget "pages" by enabling the "Scroll Wallpaper" setting in the TB settings, I figured it may be appealing to some users to scroll up and down instead of left and right.

**Describe the solution you'd like**
In the settings Under 
Features>Wallpaper Interactions>Scroll Wallpaper
There should be an aditional option where you can change the Scrolling direction to up and down as well in the home screen.

**Describe alternatives you've considered**
This Feature was mainly inspired by my experiences with the [AIO Launcher](https://play.google.com/store/apps/details?id=ru.execbit.aiolauncher) and how they executed an infinite scroll like widget menu. I never really saw this as an alternative just as much as an inspiration for a feature like this.

**Comment by TBog** [comment]
I don't understand what you call "infinite scroll".
Do you want to forgo the page snapping?

**Comment by HunterArmstrong** [comment]
> I don't understand what you call "infinite scroll".

Well, I guess it's not "infinite" scroll. Because the pages aren't infinite. I was thinking about how AIO's scroll feature was smooth and how there weren't any sort of widget pages in general.

> Do you want to forgo the page snapping? 

I don't know what "Page snapping" is. But I feel that should just be an option to other users if they want something like that.

**Comment by TBog** [comment]
Page snapping is when you lift the finger off the screen after you scroll the wallpaper and the wallpaper is snapped (automatically scrolled) to the closest page.

**Comment by HunterArmstrong** [comment]
Okay. I don't think Page snapping is something I would use. But, I don't see why another person would not use it.

**Comment by HunterArmstrong** [comment]
Any updates on this request?

**Comment by TBog** [comment]
I'll work on this after the desktop mode feature is stable because it depends on it working.

**Comment by HunterArmstrong** [comment]
Of course. Just checking in.👍👍

**Comment by HunterArmstrong** [comment]
> I'll work on this after the desktop mode feature is stable because it depends on it working.

How are the desktop mode(s) right now? Has it got more stable for TBL?

**Comment by TBog** [comment]
From my perspective I have problems with the keyboard closings and opening when I don't want and the result list icons that get refreshed too often.

Do you think the latest version is stable?

**Comment by ltGuillaume** [comment]
> the result list icons that get refreshed too often

This I recognize.

I've also seen the results list staying on top of the widgets when pressing back too soon.
