### ISSUE TITLE
[BUG] Cannot scroll widgets

### ISSUE THREAD

**Issue by yorikvanhavre** [TBog/TBLauncher#79]
Hi there!
Using TB now on a device, it's really cool!

I saw the problem below, sorry if reported already, i couldn't find anything in the list..

When adding widgets that can be scrolled (ex: todo agenda app, but the same occurs with any other widget whose area can be reduced so scrolling becomes available), they can't be scrolled with TB, while they can with others or default launcher (moving the finger over them does nothing in TB)

 - Device: Motorola Moto One Action
 - OS: Android 10
 - TB Version: 5.3

Thanks for the great app and thanks already for having a look at this!

Cheers
Yorik

**Comment by TBog** [comment]
This used to work, I'll fix it asap.
Also we need to
1. allow wallpaper scroll when widget is not handling the scroll.
2. allow user to disable widget touch handling
3. allow user to enter widget settings from long touch popup

**Comment by yorikvanhavre** [comment]
Thanks for looking into it @TBog ! I've never compiled android packages or anything, but willing to try if I can help with testing or anything.

**Comment by TBog** [comment]
I'm sorry for the delay but I don't have any time to work on the launcher right now.
This issue is my top priority right now.

**Comment by yorikvanhavre** [comment]
No worries! As we say on our project ( [FreeCAD](https://github.com/FreeCAD/FreeCAD) ) , "it's done when it's done" ;)

**Comment by TBog** [comment]
fix scroll in commit 95aaccf043bd55a33934bfdc55db1ead0c86d773
you can check it out in [Release v5.4](https://github.com/TBog/TBLauncher/releases/tag/v5.4)

**Comment by daffydock** [comment]
FY, I use ToDo Agenda widget and 5.4 addresses the issue on my device.

**Comment by yorikvanhavre** [comment]
Yes!!! It works perfectly now. Thanks a lot for the fix @TBog !!
