### ISSUE TITLE
[FEATURE] Search Provider Icon

### ISSUE THREAD

**Issue by HunterArmstrong** [TBog/TBLauncher#83]
**Is your feature request related to a problem? Please describe.**
I sometimes can't tell weather I'm searching from the regular search engine that I use or if I'm searching from a special one I added.

**Describe the solution you'd like**
I think that there should be a setting where you can change the icon from just a regular magnifying glass.

![Screenshot_20210108-091859_TinyBit launcher.jpg](https://user-images.githubusercontent.com/57189836/104046092-65365000-5194-11eb-800d-d279274e4f53.jpg)

**Comment by ltGuillaume** [comment]
Yes that would be great!

**Comment by TBog** [comment]
Merged into #140
