### ISSUE TITLE
Translation locked

### ISSUE THREAD

**Issue by comradekingu** [TBog/TBLauncher#90]
I think I locked the translations by adding the 5 strings that are in another component.

https://hosted.weblate.org/projects/tblauncher/#components

Listed as `Norsk bokmål (nb_NO-V26)` in https://hosted.weblate.org/projects/tblauncher/#languages.
Everything should be just nb_NO, like the other component is.

Edit: Presumably picked up because "values-v26" is a folder in

https://github.com/TBog/TBLauncher/tree/master/app/src/main/res

The change is https://github.com/TBog/TBLauncher/commit/aad11a62da8d6022f636086819007557d486fd02#diff-9b227b13a9a3a2e9d8c564e69cad16d25538a47f1c2c11c403d29da23a438c92

I think maybe calling it "v26-values" would escape the formatting Android/Weblate is looking for, or is it intentional somehow?

Edit2: I imagine there is a wildcard used for filemask in
https://hosted.weblate.org/settings/tblauncher/strings/#files
ala `app/src/main/res/values-*/strings.xml` but the config isn't visible to me because I am not an admin.

**Comment by TBog** [comment]
Translations for `v26` (Android 8.0 or API level 26) should go only in `strings-v26` component (not in `strings`) but I can't find a way to remove the language-v26 from `strings`

@comradekingu can you help with the config?

**Comment by TBog** [comment]
> I think maybe calling it "v26-values" would escape the formatting Android/Weblate is looking for, or is it intentional somehow?

It's an Android naming scheme, can't rename it.
