### ISSUE TITLE
Icon background always as selected in Settings

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#94]
# Description #

1. When I try to change the icon background for an app, it always returns the default one, as set in the Settings, no matter what color or transparency I choose. The goal for
me personally is to remove the background entirely.

## Steps to Reproduce ##

To reproduce the behavior:
1. Go to 'Change icon' for any app
2. Change the background color and/or transparency
3. See black background

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: latest

**Comment by TBog** [comment]
You're missing a step. It should be:
1. Go to 'Change icon'
2. Change the background color and/or transparency
3. If the Shape is set to "None / Default" you also need to touch a shape.
3. Touch the desired icon in the "Choose icon" grid.
4. See the text change from "Current icon" to "Selected icon" next to the OK button
5. Press the OK button

**Comment by ltGuillaume** [comment]
I tried that, too, setting a custom shape, then the color. The text changed to "selected icon". It still shoeed up with the default bg color.

**Comment by TBog** [comment]
> I tried that, too, setting a custom shape, then the color. The text changed to "selected icon". It still shoeed up with the default bg color.

Is the default background color the one you set in the settings?
If it's not than the application has a non-adaptive icon and I can't remove the background, I can only place that icon on a different background

**Comment by ltGuillaume** [comment]
I now see that the order in which I chose color and shape was wrong. This is very confusing, as one tends to work from top to bottom.

**Comment by TBog** [comment]
The last think you need to press is the desired icon. If you press an icon then change the color or the shape, your selection does not change. You still have selected the original icon.

**Comment by ltGuillaume** [comment]
Yes I now see that. It's immensely confusing tbh...

**Comment by TBog** [comment]
> Yes I now see that. It's immensely confusing tbh...

I suppose I can either try to:
1. reverse the order and have the icon grid at the bottom
2. or update the selection when you change shape or color

**Comment by ltGuillaume** [comment]
I think the latter would make more sense 👍

**Comment by TBog** [comment]
> I think the latter would make more sense 👍 

I'm not sure how that would work with the letter icons as those can dissappear depending on text length

**Comment by TBog** [comment]
Is this fixed? I changed the layout of the custom icon chooser.

**Comment by ltGuillaume** [comment]
It makes a lot more sense now the eventual icons are presented as the last step "Choose icon", so I'd say it's fixed.
