### ISSUE TITLE
No transparency choice for default icon background

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#95]
# Description #

Even though the icon background in the "Change icon" dialog seems to allow for transparency (but it doesn't apply the background color, see other issue), there is no way to choose the transparency for the default icon background in Settings.

## Steps to Reproduce ##

To reproduce the behavior:
1. Go to '...', then Settings
2. Click on User Interface, then Icon Background
3. The color that can be chosen does not have an alpha value

## Expected behavior ##

An alpha value, so that the background can also be removed completely.

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: latest

**Comment by TBog** [comment]
fixed in commit 7e5711d23a8f790141f504c0398c3b0ed412f500
