### ISSUE TITLE
Non-working tag filters shown in Favorites

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#99]
# Description #

When I tap the Favorites filter, it shows the tag filters in the results list. I don't think this makes sense, because when you click on them, nothing happens anyway.

## Expected behavior ##

Either don't show tags in the Favorites, or make tapping them work (activate that tag filter).

  * OS: Android 10
  * TinyBit Launcher version: Preview [build](https://github.com/TBog/TBLauncher/releases/tag/v5.4-contrast.2) for  https://github.com/TBog/TBLauncher/issues/70#issuecomment-765472295

**Comment by TBog** [comment]
Do you ever use the favorites?
Maybe we can remove it?

It is mostly an inheritance from KISS, but I started using it internally to keep custom icons from filters actions and tags.

**Comment by ltGuillaume** [comment]
To be honest, I thought about using it, but then it got filled with this. On the other hand, one might as well create a tag called `fav` or something and that would do the same I guess?

While we're on the subject of those filters, what does `Adaptive history` do exactly?

**Comment by TBog** [comment]
> While we're on the subject of those filters, what does `Adaptive history` do exactly?


`/** * Get the most used history items adaptively based on a set period of time * * @param db The SQL db * @param hours How many hours back we want to test frequency against * @param limit Maximum result size * @return Cursor */ private static Cursor getHistoryByAdaptive(SQLiteDatabase db, int hours, int limit) { // order history based on frequency String sql = "SELECT record, count(*) FROM history " + "WHERE timeStamp >= 0 " + "AND timeStamp >" + (System.currentTimeMillis() - (hours * 3600000)) + " GROUP BY record " + " ORDER BY count(*) DESC " + " LIMIT " + limit; return db.rawQuery(sql, null); }
`

**Comment by ltGuillaume** [comment]
Ah so most popular apps/shortcuts looking only at the last x hours.

Wow, that `getHistoryByFrecency()`'s `ORDER BY` part is a bit tricky to understand.

**Comment by ltGuillaume** [comment]
Oh wait, I think you do need to have Favorites if you want to put an app or shortcut in the quick list, right?

**Comment by TBog** [comment]
> Wow, that `getHistoryByFrecency()`'s `ORDER BY` part is a bit tricky to understand, but it takes all history in account to judge the popularity, instead of just the last x hours, right?

It's inherited from KISS, but let's try to find what it does
`ORDER BY`
`count(*) * 1.0 / (select count(*) from history LIMIT " + historyWindowSize + ") / ((SELECT _id FROM history ORDER BY _id DESC LIMIT 1) - max(_id) + 0.001)`

* `count(*)` how many rows the SELECT returns
* `(select count(*) from history LIMIT " + historyWindowSize + ")` this returns the number on records in the whole history, the LIMIT clause is useless as the SELECT will only return one row, the COUNT(*)
* `((SELECT _id FROM history ORDER BY _id DESC LIMIT 1) - max(_id)`
  * SELECT will return the id of the last entry
  * MAX will return the greatest  id from the initial query (`(SELECT * FROM history ORDER BY _id DESC LIMIT " + historyWindowSize + " )`).
  * I think the result is `0`

This query should be fixed IMHO. It's the first time I looked at what it does instead of reading the comment before it and assuming it does that.

**Comment by TBog** [comment]
remove actions and filters from result list with commit a28c859e966bc53c1df631c350b0166afa467dbe

**Comment by ltGuillaume** [comment]
Yeah, it does seem to be broken. From the description, I think it's useful compared to adaptive with a small time window, not so much when you choose a large time window for adaptive.

**Comment by ltGuillaume** [comment]
Are you sure that filters and actions  shouldn't be available to the user at all unless they're added to the results list? Currently they won't show up when searched for either.

**Comment by TBog** [comment]
> Are you sure that filters and actions  shouldn't be available to the user at all unless they're added to the results list? Currently they won't show up when searched for either. 

Not sure what you mean.
Filters and actions are intended to be used in the QuickList. 
I may be convinced to add actions to the result list when searching, but filters have no place there.

**Comment by ltGuillaume** [comment]
That's all right. I just thought there might be a use case where you wouldn't want to have a tag filter on your quick list, but still would want to list the apps within it. For example, if you have apps you still want to test, so you add the tag "test" or "new", but don't want that tag on display in the quick list all the time.

Come to think of it, for that use case it would be even better if there were a filter "untagged" for that, so the tag "test"/"new" wouldn't be necessary to isolate the new apps from the "tagged" regularly used ones.

**Comment by TBog** [comment]
> That's all right. I just thought there might be a use case where you wouldn't want to have a tag filter on your quick list, but still would want to list the apps within it. For example, if you have apps you still want to test, so you add the tag "test" or "new", but don't want that tag on display in the quick list all the time.

You search for the tag name. What would help is to have a filter to only show matches in the tags (not the app name).

> Come to think of it, for that use case it would be even better if there were a filter "untagged" for that, so the tag "test"/"new" wouldn't be necessary to isolate the new apps from the (tagged) regularly used ones. I think I would use that on a daily basis: test apps, have them listed under "untagged" easily, then if I want to keep them, I tag them appropriately. It sort of creates an "inbox" in line with the getting things done system. I suppose that's a whole other feature request and this issue could be done with. Should I create a new issue for this?

That we can do. Please add an issue for the "untagged" feature. Not sure we can have it as a filter, but at least an action we can add.

**Comment by ltGuillaume** [comment]
> You search for the tag name. What would help is to have a filter to only show matches in the tags (not the app name).

Yes, that's right, if one has the tags shown below the results, true.

> That we can do. Please add an issue for the "untagged" feature. Not sure we can have it as a filter, but at least an action we can add.

Done. I'd like to learn what the difference really is between an action and a filter in such a case. I see actions that do a specific calculation/query (Recent, Most accessed, Recent and frequent, Adaptive), but I also see actions that in effect look like a filter (Favorites, Apps/Contacts/Shortcuts A-Z/Z-A).

**Comment by TBog** [comment]
> I'd like to learn what the difference really is between an action and a filter in such a case. I see actions that do a specific calculation/query (Recent, Most accessed, Recent and frequent, Adaptive), but I also see actions that in effect look like a filter (Favorites, Apps/Contacts/Shortcuts A-Z/Z-A).

* filters have a provider and a text
* actions only have a provider

- The provider is used to fill the result list with entries 
- When the result list is empty the filter fills it with all the entries from the provider
- When there are entries in the results list, the filter will use the text and match it against those entries. 
Right now I'm only able to match based on entry ID.
  - Apps have IDs that start with `app://`
  - Shortcuts have IDs that start with `shortcut://`
  - Contacts have IDs that start with `contact://`
- History action has a provider
- Favorites action has a provider
- Apps/Contacts/Shortcuts action has a provider (same one used by the apps filter) 
- After an action gets the entries from the provider it sorts them before sending them to the result list

**Comment by ltGuillaume** [comment]
I just checked the https://github.com/TBog/TBLauncher/releases/tag/v5.4-modes.1 build and my tag filters are still in the Favorites (without working).

**Comment by TBog** [comment]
> I just checked the https://github.com/TBog/TBLauncher/releases/tag/v5.4-modes.1 build and my tag filters are still in the Favorites (without working). 

tags are not filters.
I'll remove them too.

**Comment by ltGuillaume** [comment]
I just noticed that, sorry. At first I thought that clicking a tag _in the quick list_ would apply a tag "filter" to the search text (which would be nice actually), especially because of the somewhat strange behavior I mentioned in #105.

**Comment by TBog** [comment]
`actions` added back as they work now
in commit cbda1bf6f60890d16058fd7a6be0991e15aed252
